'use client'

import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Header } from '@/components/layout/Header'
import { Check, Copy, ExternalLink } from 'lucide-react'
import styles from './Admission.module.css'
import { AdmissionTitle } from './shared'
import { AnalystPicker } from './AnalystPicker'
import { ADMISSION_BREAKS, ADMISSION_MONTHLY_HOURS, ADMISSION_MONTHLY_HOURS_OPTIONS, ADMISSION_SCHEDULES, type AdmissionPosition, findPosition as findPositionIn, formatBRL, hasSalaryForUnit, salaryForUnit } from '@/lib/admission/positions'
import { COUNCIL_DOCUMENT_KEYS, isDocumentApplicableToPosition } from '@/lib/admission/documentRules'

type Collaborator={id:string;erpnextId:string;employeeName:string;personalEmail?:string|null;cellNumber?:string|null;designation?:string|null;department?:string|null;dateOfJoining?:string|null;unitId?:string|null;unit?:{name:string}|null}
type Meta={units:{id:string;name:string}[];candidates:{id:string;nome:string;email?:string;telefone?:string;vagaId:string;vaga:{cargo:string;unidadeId?:string}}[];vacancies:{id:string;titulo:string;cargo:string;setor?:string|null;unidadeId?:string|null;unit?:{name:string}|null;salarioMin?:number|null;horarioTrabalho?:string|null;cargaHoraria?:string|null;tipoContrato?:'DETERMINADO'|'INDETERMINADO'|null;requisicaoNextId?:string|null;nomeColaboradorSaiu?:string|null;dataInicioIntegracao?:string|null;analistas:{id:string}[]}[];users:{id:string;name:string}[];documentTypes:{id:string;key:string;name:string;description?:string|null;required:boolean;defaultSelected:boolean}[];collaborators:Collaborator[];positions:AdmissionPosition[]}
const admissionSteps=['Candidato','Vaga e unidade','Dados da contratação','Documentos necessários','Revisão']
const updateSteps=['Colaborador','Seções','Documentos','Responsável e prazo','Revisão']
type Mode='ADMISSION'|'REGISTRATION_UPDATE'
const updateSections=[['personal','Dados pessoais e contato'],['address','Endereço'],['bank','Dados bancários'],['dependents','Dependentes'],['transport','Vale-transporte'],['documents','Documentos específicos'],['photo','Foto do crachá']] as const

export function AdmissionNew({mode='ADMISSION'}:{mode?:Mode}){
 const router=useRouter(),[meta,setMeta]=useState<Meta|null>(null),[step,setStep]=useState(1),[saving,setSaving]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{publicUrl:string;expiresAt:string;admission:{id:string;protocol:string}}|null>(null)
 const [form,setForm]=useState({candidateId:'',candidateName:'',candidateEmail:'',candidatePhone:'',vacancyId:'',unitId:'',jobTitle:'',department:'',hireDate:'',hazardPayPercentage:'20',workSchedule:'',breakSchedule:'',monthlyHours:String(ADMISSION_MONTHLY_HOURS),contractType:'CLT - prazo indeterminado',experienceDays:'90',contractEndDate:'',ownerId:'',validityDays:'7'})
 const [docIds,setDocIds]=useState<string[]>([])
 const processType=mode,steps=mode==='REGISTRATION_UPDATE'?updateSteps:admissionSteps,[collaboratorId,setCollaboratorId]=useState(''),[requestedSections,setRequestedSections]=useState<string[]>([]),[analystIds,setAnalystIds]=useState<string[]>([])
 useEffect(()=>{fetch('/api/admissao-digital/meta').then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||'Não foi possível carregar os colaboradores.');return data}).then((m:Meta)=>{setMeta(m);setDocIds(m.documentTypes.filter(d=>d.required||d.defaultSelected).map(d=>d.id))}).catch(err=>setError(err instanceof Error?err.message:'Não foi possível carregar os colaboradores.'))},[])
 // Cargos vêm do cadastro (Administração → Cargos) com salário por unidade.
 const findPosition=(cargo?:string|null)=>findPositionIn(meta?.positions||[],cargo)
 const position=findPosition(form.jobTitle),salary=salaryForUnit(position,form.unitId,Number(form.monthlyHours))
 const unitPositions=useMemo(()=>(meta?.positions||[]).filter(p=>!form.unitId||hasSalaryForUnit(p,form.unitId)),[meta,form.unitId])
 const departments=useMemo(()=>Array.from(new Set((meta?.positions||[]).map(p=>p.departamento).filter((d):d is string=>!!d))).sort(),[meta])
 function chooseCargo(cargo:string){const pos=findPosition(cargo);setForm(f=>({...f,jobTitle:pos?.name||'',department:pos?.departamento||f.department}))}
 const candidate=useMemo(()=>meta?.candidates.find(c=>c.id===form.candidateId),[meta,form.candidateId]);const vacancy=useMemo(()=>meta?.vacancies.find(v=>v.id===form.vacancyId),[meta,form.vacancyId])
 const admissionDocumentTypes=useMemo(()=>(meta?.documentTypes||[]).filter(document=>isDocumentApplicableToPosition(document.key,form.jobTitle)),[meta,form.jobTitle])
 useEffect(()=>{if(processType!=='ADMISSION'||!meta)return;const council=meta.documentTypes.filter(document=>COUNCIL_DOCUMENT_KEYS.has(document.key));setDocIds(ids=>{const withoutCouncil=ids.filter(id=>!council.some(document=>document.id===id));return isDocumentApplicableToPosition('coren_carteirinha',form.jobTitle)?Array.from(new Set([...withoutCouncil,...council.filter(document=>document.required||document.defaultSelected).map(document=>document.id)])):withoutCouncil})},[form.jobTitle,meta,processType])
 function change(name:string,value:string){setForm(f=>({...f,[name]:value}))}
 function chooseCandidate(id:string){const c=meta?.candidates.find(x=>x.id===id),v=meta?.vacancies.find(x=>x.id===c?.vagaId);setForm(f=>({...f,candidateId:id,candidateName:c?.nome||'',candidateEmail:c?.email||'',candidatePhone:c?.telefone||'',vacancyId:c?.vagaId||f.vacancyId,jobTitle:findPosition(c?.vaga.cargo)?.name||f.jobTitle,department:findPosition(c?.vaga.cargo)?.departamento||f.department,unitId:c?.vaga.unidadeId||f.unitId,...(v?vacancyFields(v,f):{})}))}
 function chooseVacancy(id:string){const v=meta?.vacancies.find(x=>x.id===id);setForm(f=>({...f,vacancyId:id,...(v?vacancyFields(v,f):{})}))}
 // Preenche tudo o que a vaga já define; o RH só edita se precisar.
 function vacancyFields(v:Meta['vacancies'][number],f:typeof form){const pos=findPosition(v.cargo),analyst=v.analistas.find(a=>meta?.users.some(u=>u.id===a.id));return{unitId:v.unidadeId||f.unitId,jobTitle:pos?.name||f.jobTitle,department:pos?.departamento||f.department,workSchedule:(ADMISSION_SCHEDULES as readonly string[]).includes(v.horarioTrabalho||'')?v.horarioTrabalho!:f.workSchedule,contractType:v.tipoContrato==='DETERMINADO'?'CLT - prazo determinado':v.tipoContrato==='INDETERMINADO'?'CLT - prazo indeterminado':f.contractType,hireDate:f.hireDate||v.dataInicioIntegracao?.slice(0,10)||'',ownerId:f.ownerId||analyst?.id||''}}
 function chooseCollaborator(id:string){const collaborator=meta?.collaborators.find(item=>item.id===id);setCollaboratorId(id);setForm(value=>({...value,candidateName:collaborator?.employeeName||'',candidateEmail:collaborator?.personalEmail||'',candidatePhone:collaborator?.cellNumber||'',unitId:collaborator?.unitId||'',jobTitle:collaborator?.designation||'Colaborador',department:collaborator?.department||'',hireDate:collaborator?.dateOfJoining?.slice(0,10)||new Date().toISOString().slice(0,10),contractType:'Não informado'}))}
 async function submit(e:FormEvent){e.preventDefault();if(processType==='ADMISSION'&&step===4&&!docIds.length){setError('Selecione ao menos um documento a solicitar.');return}if(processType==='ADMISSION'&&step===2&&(!position||!hasSalaryForUnit(position,form.unitId))){setError('Selecione um cargo com salário cadastrado para a unidade.');return}if(processType==='ADMISSION'&&step===3&&salary===null){setError(`O cargo não tem salário cadastrado para ${form.monthlyHours} horas mensais nesta unidade.`);return}if(processType==='REGISTRATION_UPDATE'&&step===1&&!collaboratorId){setError('Selecione o colaborador.');return}if(processType==='REGISTRATION_UPDATE'&&step===2&&!requestedSections.length){setError('Selecione ao menos uma seção.');return}if(processType==='REGISTRATION_UPDATE'&&step===3&&requestedSections.includes('documents')&&!docIds.length){setError('Selecione ao menos um documento.');return}if(step<5){setError('');setStep(s=>s+1);return}setSaving(true);setError('');try{const payload={...form,processType,collaboratorId:collaboratorId||undefined,requestedSections,documentTypeIds:processType==='REGISTRATION_UPDATE'&&!requestedSections.includes('documents')?[]:docIds,hazardPayPercentage:form.hazardPayPercentage?Number(form.hazardPayPercentage):undefined,experienceDays:form.experienceDays?Number(form.experienceDays):undefined,validityDays:Number(form.validityDays),contractEndDate:form.contractEndDate||undefined,ownerId:form.ownerId||undefined,analystIds:analystIds.filter(id=>id!==form.ownerId),candidateId:form.candidateId||undefined,vacancyId:form.vacancyId||undefined};const r=await fetch('/api/admissao-digital/admissoes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||`Não foi possível criar ${processType==='REGISTRATION_UPDATE'?'a atualização cadastral':'a admissão'}.`);setResult(j)}catch(err){setError(err instanceof Error?err.message:'Erro inesperado.')}finally{setSaving(false)}}
 if(result)return <><Header title={processType==='REGISTRATION_UPDATE'?'Nova atualização cadastral':'Nova admissão'}/><div className={styles.module}><div className={styles.content} style={{maxWidth:680}}><section className={styles.card} style={{textAlign:'center',padding:36}}><div style={{width:52,height:52,borderRadius:'50%',background:'#E6F4EC',color:'#1E8E5A',display:'grid',placeItems:'center',margin:'0 auto 16px'}}><Check size={25}/></div><h1 className={styles.title} style={{fontSize:20}}>{processType==='REGISTRATION_UPDATE'?'Atualização cadastral criada':'Admissão criada'} com sucesso</h1><p className={styles.subtitle} style={{margin:'0 auto 20px'}}>O link individual foi gerado e é válido até {new Date(result.expiresAt).toLocaleDateString('pt-BR')}.</p><div className={`${styles.input} ${styles.mono}`} style={{height:'auto',padding:12,wordBreak:'break-all',marginBottom:12}}>{result.publicUrl}</div><div className={styles.actions} style={{justifyContent:'center'}}><button className={styles.buttonPrimary} onClick={()=>navigator.clipboard.writeText(result.publicUrl)}><Copy size={14}/>Copiar link</button><a className={styles.button} href={result.publicUrl} target="_blank"><ExternalLink size={14}/>Abrir portal</a><button className={styles.button} onClick={()=>router.push(`/admissao-digital/admissoes/${result.admission.id}`)}>Abrir processo</button></div></section></div></div></>
 return <><Header title={processType==='REGISTRATION_UPDATE'?'Nova atualização cadastral':'Nova admissão'} subtitle={processType==='REGISTRATION_UPDATE'?'Atualização Cadastral':'Admissão Digital'}/><div className={styles.module}><div className={styles.content} style={{maxWidth:860}}><AdmissionTitle tourId="new-heading" title={processType==='REGISTRATION_UPDATE'?'Nova atualização cadastral':'Nova admissão'} subtitle={processType==='REGISTRATION_UPDATE'?'O colaborador revisa somente as seções escolhidas; o RH confirma antes de enviar ao ERPNext.':'Os dados definidos aqui não poderão ser alterados pelo candidato.'}/><div className={styles.stepper} data-admission-tour="new-stepper">{steps.map((label,i)=><div key={label} className={`${styles.step} ${i+1<step?styles.stepDone:i+1===step?styles.stepCurrent:''}`}><span className={styles.stepCircle}>{i+1<step?<Check size={12}/>:i+1}</span>{i<steps.length-1&&<span className={styles.stepLine}/>}</div>)}</div><form onSubmit={submit} className={styles.card} data-admission-tour="new-form">
  {step===1&&<>{processType==='ADMISSION'?<><h2 className={styles.cardTitle}>Candidato</h2><p className={styles.subtitle} style={{margin:'4px 0 18px'}}>Selecione um candidato aprovado ou preencha manualmente.</p><div className={styles.formGrid}><Field label="Candidato aprovado"><SearchSelect id="candidate" items={(meta?.candidates||[]).map(c=>({id:c.id,text:`${c.nome} · ${c.vaga.cargo}`}))} value={form.candidateId} onChoose={chooseCandidate} emptyLabel="Cadastro manual" placeholder="Digite o nome do candidato ou deixe em branco para cadastro manual" notFound="Nenhum candidato encontrado. Continue para cadastro manual."/></Field><Field label="Nome completo *"><input required className={styles.input} value={form.candidateName} onChange={e=>change('candidateName',e.target.value)}/></Field><Field label="E-mail"><input type="email" className={styles.input} value={form.candidateEmail} onChange={e=>change('candidateEmail',e.target.value)}/></Field><Field label="Telefone"><input inputMode="tel" className={styles.input} value={form.candidatePhone} onChange={e=>change('candidatePhone',e.target.value)}/></Field></div></>:<><h2 className={styles.cardTitle}>Colaborador</h2><p className={styles.subtitle} style={{margin:'4px 0 18px'}}>Busque o colaborador ativo que deverá revisar os dados ou enviar documentos.</p><Field label="Colaborador ativo *"><SearchSelect id="collaborator" items={(meta?.collaborators||[]).map(c=>({id:c.id,text:`${c.employeeName} · ${c.designation||'Sem cargo'} · ${c.unit?.name||'Sem unidade'}`,search:c.department||''}))} value={collaboratorId} onChoose={chooseCollaborator} emptyLabel="Nenhum colaborador selecionado" placeholder="Digite o nome, cargo ou unidade do colaborador" notFound="Nenhum colaborador ativo encontrado."/></Field></>}</>}
  {step===2&&processType==='REGISTRATION_UPDATE'&&<><h2 className={styles.cardTitle}>O que deve ser atualizado?</h2><p className={styles.subtitle} style={{margin:'4px 0 18px'}}>O colaborador verá somente as seções selecionadas. Os dados existentes serão apresentados para conferência.</p><div className={styles.metricList}>{updateSections.map(([key,label])=><label className={styles.docRow} key={key} style={{cursor:'pointer'}}><input type="checkbox" checked={requestedSections.includes(key)} onChange={e=>setRequestedSections(value=>e.target.checked?[...value,key]:value.filter(item=>item!==key))}/><strong>{label}</strong></label>)}</div></>}
  {step===2&&processType==='ADMISSION'&&<><h2 className={styles.cardTitle}>Vaga e unidade</h2><p className={styles.subtitle} style={{margin:'4px 0 18px'}}>O candidato verá apenas Unidade, Cargo e Departamento. A vaga serve só para você vincular a admissão à vaga de substituição.</p><div className={styles.formGrid}><Field label="Vaga de substituição (opcional)"><SearchSelect id="vacancy" items={(meta?.vacancies||[]).map(v=>({id:v.id,text:[v.titulo,v.horarioTrabalho,v.nomeColaboradorSaiu&&`subst. ${v.nomeColaboradorSaiu}`,v.requisicaoNextId].filter(Boolean).join(' · '),search:`${v.cargo} ${v.unit?.name||''} ${v.setor||''}`}))} value={form.vacancyId} onChoose={chooseVacancy} emptyLabel="Sem vaga vinculada" placeholder="Digite cargo, unidade ou RP da vaga" notFound="Nenhuma vaga encontrada."/></Field><Field label="Unidade *"><select required className={styles.select} value={form.unitId} onChange={e=>change('unitId',e.target.value)}><option value="">Selecione</option>{meta?.units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Cargo *"><select required className={styles.select} value={position?.name||''} onChange={e=>chooseCargo(e.target.value)}><option value="">{form.unitId?'Selecione':'Selecione a unidade primeiro'}</option>{position&&!unitPositions.includes(position)&&<option value={position.name}>{position.name} (sem salário nesta unidade)</option>}{unitPositions.map(p=><option key={p.id} value={p.name}>{p.name}{form.unitId&&salaryForUnit(p,form.unitId,Number(form.monthlyHours))!==null?` · ${formatBRL(salaryForUnit(p,form.unitId,Number(form.monthlyHours))!)}`:''}</option>)}</select>{form.unitId&&!unitPositions.length&&<p className={styles.hint}>Nenhum cargo com salário para esta unidade. Cadastre em Administração → Cargos.</p>}{position&&form.unitId&&!hasSalaryForUnit(position,form.unitId)&&<p className={styles.error}>Este cargo não tem salário cadastrado para a unidade escolhida.</p>}</Field><Field label="Departamento *">{position?.departamento?<div className={styles.input} style={{display:'flex',alignItems:'center',background:'#F6F8F8'}} aria-readonly="true">{position.departamento}</div>:<select required className={styles.select} value={form.department} onChange={e=>change('department',e.target.value)}><option value="">Selecione</option>{departments.map(d=><option key={d} value={d}>{d}</option>)}</select>}</Field>{position&&salary!==null&&<Field label={`Salário (${form.monthlyHours} h mensais)`}><div className={styles.input} style={{display:'flex',alignItems:'center',background:'#F6F8F8'}} aria-readonly="true">{formatBRL(salary)}</div></Field>}</div></>}
  {step===3&&processType==='REGISTRATION_UPDATE'&&<><h2 className={styles.cardTitle}>Documentos específicos</h2>{requestedSections.includes('documents')?<><p className={styles.subtitle} style={{margin:'4px 0 18px'}}>Selecione somente o que deverá ser apresentado novamente.</p><div className={styles.metricList}>{meta?.documentTypes.map(d=><label className={styles.docRow} key={d.id} style={{cursor:'pointer'}}><input type="checkbox" checked={docIds.includes(d.id)} onChange={e=>setDocIds(ids=>e.target.checked?Array.from(new Set([...ids,d.id])):ids.filter(x=>x!==d.id))}/><strong>{d.name}</strong>{d.description&&<div className={styles.itemMeta} style={{marginLeft:22}}>{d.description}</div>}</label>)}</div></>:<div className={styles.empty}>Nenhum documento foi solicitado. Esta etapa será ignorada no portal.</div>}</>}
  {step===3&&processType==='ADMISSION'&&<><h2 className={styles.cardTitle}>Dados da contratação</h2><p className={styles.subtitle} style={{margin:'4px 0 18px'}}>Estas informações aparecem ao candidato somente para leitura.</p><div className={styles.formGrid}><Field label="Data prevista de admissão *"><input required type="date" className={styles.input} value={form.hireDate} onChange={e=>change('hireDate',e.target.value)}/></Field><Field label="Salário (definido pelo cargo)"><div className={styles.input} style={{display:'flex',alignItems:'center',background:'#F6F8F8'}} aria-readonly="true">{salary!==null?formatBRL(salary):position?`Sem salário para ${form.monthlyHours} horas nesta unidade`:'Selecione o cargo e a unidade na etapa anterior'}</div></Field><Field label="Insalubridade (%)"><input type="number" min="0" max="100" className={styles.input} value={form.hazardPayPercentage} onChange={e=>change('hazardPayPercentage',e.target.value)}/></Field><Field label="Horário *"><select required className={styles.select} value={form.workSchedule} onChange={e=>change('workSchedule',e.target.value)}><option value="">Selecione</option>{ADMISSION_SCHEDULES.map(h=><option key={h} value={h}>{h}</option>)}</select></Field><Field label="Intervalo"><select className={styles.select} value={form.breakSchedule} onChange={e=>change('breakSchedule',e.target.value)}><option value="">Selecione</option>{ADMISSION_BREAKS.map(h=><option key={h} value={h}>{h}</option>)}</select></Field><Field label="Carga horária mensal *"><select required className={styles.select} value={form.monthlyHours} onChange={e=>change('monthlyHours',e.target.value)}>{ADMISSION_MONTHLY_HOURS_OPTIONS.map(h=><option key={h} value={h}>{h} horas</option>)}</select></Field><Field label="Tipo de contrato *"><input required className={styles.input} value={form.contractType} onChange={e=>change('contractType',e.target.value)}/></Field><Field label="Experiência (dias)"><input type="number" className={styles.input} value={form.experienceDays} onChange={e=>change('experienceDays',e.target.value)}/></Field><Field label="Analista responsável (principal)"><select className={styles.select} value={form.ownerId} onChange={e=>change('ownerId',e.target.value)}><option value="">Eu mesmo(a)</option>{meta?.users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Outros analistas responsáveis"><AnalystPicker users={meta?.users||[]} ownerId={form.ownerId} value={analystIds} onChange={setAnalystIds}/></Field><Field label="Validade do link"><select className={styles.select} value={form.validityDays} onChange={e=>change('validityDays',e.target.value)}><option value="3">3 dias</option><option value="7">7 dias</option><option value="14">14 dias</option><option value="30">30 dias</option></select></Field></div></>}
  {step===4&&processType==='REGISTRATION_UPDATE'&&<><h2 className={styles.cardTitle}>Responsável e prazo</h2><div className={styles.formGrid}><Field label="Analista responsável (principal)"><select className={styles.select} value={form.ownerId} onChange={e=>change('ownerId',e.target.value)}><option value="">Eu mesmo(a)</option>{meta?.users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Outros analistas responsáveis"><AnalystPicker users={meta?.users||[]} ownerId={form.ownerId} value={analystIds} onChange={setAnalystIds}/></Field><Field label="Validade do link"><select className={styles.select} value={form.validityDays} onChange={e=>change('validityDays',e.target.value)}><option value="3">3 dias</option><option value="7">7 dias</option><option value="14">14 dias</option><option value="30">30 dias</option></select></Field></div><div className={styles.docRow} style={{marginTop:18,background:'#FFF9EE'}}><strong>Revisão obrigatória do RH</strong><div className={styles.itemMeta}>As alterações somente serão enviadas ao ERPNext depois da confirmação final do RH.</div></div></>}
  {step===4&&processType==='ADMISSION'&&<><h2 className={styles.cardTitle}>Documentos necessários</h2><p className={styles.subtitle} style={{margin:'4px 0 18px'}}>Marque somente os documentos que serão solicitados nesta admissão. A lista já considera o cargo escolhido; documentos militares e de dependentes serão exigidos apenas quando as respostas do candidato indicarem que se aplicam. A foto do crachá, o formulário admissional e o vale-transporte já são feitos no portal.</p><div className={styles.metricList}>{admissionDocumentTypes.map(d=><label className={styles.docRow} key={d.id} style={{cursor:'pointer'}}><input type="checkbox" checked={docIds.includes(d.id)} onChange={e=>setDocIds(ids=>e.target.checked?Array.from(new Set([...ids,d.id])):ids.filter(x=>x!==d.id))}/> <strong>{d.name}</strong><span className={styles.itemMeta}> · {d.required?'Obrigatório quando aplicável':'Opcional'}</span>{d.description&&<div className={styles.itemMeta} style={{marginLeft:22}}>{d.description}</div>}</label>)}</div></>}
  {step===5&&processType==='REGISTRATION_UPDATE'&&<><h2 className={styles.cardTitle}>Revise antes de enviar</h2><p className={styles.subtitle} style={{margin:'4px 0 18px'}}>O colaborador receberá um link seguro por e-mail e WhatsApp.</p><div className={styles.summaryGrid}><Summary label="Colaborador" value={meta?.collaborators.find(c=>c.id===collaboratorId)?.employeeName||'—'}/><Summary label="Seções" value={`${requestedSections.length} selecionadas`}/><Summary label="Documentos" value={requestedSections.includes('documents')?`${docIds.length} solicitados`:'Nenhum'}/><Summary label="Validade" value={`${form.validityDays} dias`}/><Summary label="Envio ao ERPNext" value="Após revisão do RH"/></div></>}
  {step===5&&processType==='ADMISSION'&&<><h2 className={styles.cardTitle}>Revise antes de enviar</h2><p className={styles.subtitle} style={{margin:'4px 0 18px'}}>Ao confirmar, o sistema gera um link individual seguro.</p><div className={styles.summaryGrid}><Summary label="Candidato" value={form.candidateName}/><Summary label="Cargo" value={form.jobTitle}/><Summary label="Departamento" value={position?.departamento||form.department||'—'}/><Summary label="Salário" value={salary!==null?formatBRL(salary):'—'}/><Summary label="Horário" value={form.workSchedule||'—'}/><Summary label="Intervalo" value={form.breakSchedule||'—'}/><Summary label="Carga horária" value={`${form.monthlyHours} horas mensais`}/><Summary label="Analista responsável" value={meta?.users.find(u=>u.id===form.ownerId)?.name||'Eu mesmo(a)'}/><Summary label="Outros analistas" value={analystIds.map(id=>meta?.users.find(u=>u.id===id)?.name).filter(Boolean).join(', ')||'—'}/><Summary label="Documentos" value={`${docIds.length} solicitados`}/><Summary label="Unidade" value={meta?.units.find(u=>u.id===form.unitId)?.name||'—'}/><Summary label="Admissão" value={form.hireDate?new Date(`${form.hireDate}T12:00:00`).toLocaleDateString('pt-BR'):'—'}/><Summary label="Contrato" value={form.contractType}/><Summary label="Link" value={`${form.validityDays} dias`}/></div></>}
  {error&&<p className={styles.error}>{error}</p>}<div className={styles.actions} data-admission-tour="new-actions" style={{justifyContent:'space-between',marginTop:24}}><button type="button" className={styles.button} onClick={()=>step===1?router.back():setStep(s=>s-1)}>{step===1?'Cancelar':'Voltar'}</button><button className={styles.buttonPrimary} disabled={saving}>{saving?'Criando…':step===5?processType==='REGISTRATION_UPDATE'?'Criar atualização e gerar link':'Criar admissão e gerar link':'Continuar'}</button></div>
 </form></div></div></>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className={styles.field}><label className={styles.label}>{label}</label>{children}</div>}
function Summary({label,value}:{label:string;value:string}){return <div><div className={styles.summaryLabel}>{label}</div><div className={styles.summaryValue}>{value}</div></div>}
const searchKey=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
function SearchSelect({id,items,value,onChoose,emptyLabel,placeholder,notFound}:{id:string;items:{id:string;text:string;search?:string}[];value:string;onChoose:(id:string)=>void;emptyLabel:string;placeholder:string;notFound:string}){const selected=items.find(item=>item.id===value),[text,setText]=useState(''),[open,setOpen]=useState(false),[active,setActive]=useState(0),inputRef=useRef<HTMLInputElement>(null),closeTimer=useRef<ReturnType<typeof setTimeout>>(),listId=`suggest-${id}`
 useEffect(()=>{if(selected)setText(selected.text)},[selected])
 useEffect(()=>()=>clearTimeout(closeTimer.current),[])
 const matches=useMemo(()=>{const terms=selected?[]:searchKey(text).split(/\s+/).filter(Boolean);return items.filter(item=>{const key=searchKey(`${item.text} ${item.search||''}`);return terms.every(term=>key.includes(term))}).slice(0,50)},[text,items,selected])
 const options=[{id:'',text:emptyLabel},...matches]
 function choose(id:string){clearTimeout(closeTimer.current);if(!id)setText('');onChoose(id);setOpen(false);inputRef.current?.blur()}
 return <div className={styles.suggest}><input ref={inputRef} className={styles.input} placeholder={placeholder} autoComplete="off" role="combobox" aria-expanded={open} aria-controls={listId} aria-autocomplete="list" value={text} onFocus={()=>{clearTimeout(closeTimer.current);setOpen(true);setActive(0)}} onBlur={()=>{closeTimer.current=setTimeout(()=>setOpen(false),250)}} onChange={event=>{setText(event.target.value);if(value)onChoose('');setOpen(true);setActive(0)}} onKeyDown={event=>{if(!open)return;if(event.key==='ArrowDown'){event.preventDefault();setActive(i=>Math.min(i+1,options.length-1))}else if(event.key==='ArrowUp'){event.preventDefault();setActive(i=>Math.max(i-1,0))}else if(event.key==='Enter'){event.preventDefault();choose(options[active].id)}else if(event.key==='Escape')setOpen(false)}}/>{open&&<ul id={listId} role="listbox" className={styles.suggestList}>{options.map((option,index)=><li key={option.id||'empty'} role="option" aria-selected={index===active} className={index===active?styles.suggestActive:undefined} onMouseDown={event=>event.preventDefault()} onClick={()=>choose(option.id)}>{option.text}</li>)}</ul>}{open&&text&&!selected&&!matches.length&&<p className={styles.hint}>{notFound}</p>}</div>}
