'use client'

import { useCallback, useEffect, useState } from 'react'
import { Header } from '@/components/layout/Header'
import { Copy, RefreshCw, ShieldX, Send } from 'lucide-react'
import styles from './Admission.module.css'
import { ErrorState, formatDate, formatDateTime, StatusBadge } from './shared'

type Detail={id:string;protocol:string;candidateName:string;candidateEmail?:string;candidatePhone?:string;jobTitle:string;department?:string;hireDate:string;salary?:number;workSchedule?:string;contractType:string;status:string;progress:number;lastActivityAt:string;unit:{name:string};owner?:{name:string};tokens:{expiresAt:string;revokedAt?:string}[];documents:{id:string;status:string;rejectionReason?:string;version:number;uploadedAt?:string;mimeType?:string;type:{key:string;name:string}}[];badgePhotos:{id:string;confirmedAt?:string}[];faceVerifications:{id:string;provider:string;status:string;attempts:number;resultMetadata?:Record<string,unknown>;completedAt?:string}[];dependents:unknown[];fields:{section:string;key:string;value:unknown}[];erpnextSyncs:{status:string;attempts:number;lastError?:string;lastSyncedAt?:string}[];auditLogs:{id:string;action:string;actorName?:string;actorType:string;createdAt:string}[]}
const tabs=['Visão geral','Dados pessoais','Dependentes','Vale-transporte','Documentos','Foto e validação facial','Contratos e assinatura','ERPNext','Histórico']

export function AdmissionDetail({id}:{id:string}){
 const [data,setData]=useState<Detail|null>(null),[active,setActive]=useState(0),[error,setError]=useState(''),[toast,setToast]=useState('')
 const load=useCallback(async()=>{try{const r=await fetch(`/api/admissao-digital/admissoes/${id}`);if(!r.ok)throw new Error();setData(await r.json())}catch{setError('Não foi possível carregar a admissão.')}},[id]);useEffect(()=>{load()},[load])
 async function action(name:string,body:Record<string,unknown>={}){if(['invalidate-link','cancel','approve-face','request-face-retry'].includes(name)&&!confirm('Confirma esta ação? Ela será registrada na auditoria.'))return;const r=await fetch(`/api/admissao-digital/admissoes/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:name,...body})});const j=await r.json();if(!r.ok){setToast(j.error||'Ação não concluída.');return}if(j.publicUrl){await navigator.clipboard.writeText(j.publicUrl);setToast('Novo link copiado.')}else setToast('Ação concluída.');load();setTimeout(()=>setToast(''),3000)}
 if(error)return <><Header title="Admissão Digital"/><div className={styles.module}><ErrorState message={error} retry={load}/></div></>
 if(!data)return <><Header title="Admissão Digital"/><div className={styles.module}><div className={styles.skeleton}/></div></>
 const steps=[['Dados pessoais',18],['Documentos',55],['Foto e validação facial',74],['Documentos admissionais',82],['Assinatura',94],['Integração ERPNext',98],['Conclusão',100]] as const
 const face=data.faceVerifications[0],identity=data.documents.find(document=>document.type.key==='rg_frente'),faceMetadata=face?.resultMetadata||{},similarity=typeof faceMetadata.similarity==='number'?faceMetadata.similarity:null
 return <><Header title={data.candidateName} subtitle={data.protocol}/><div className={styles.detailHeader}><div className={styles.content}><div className={styles.titleRow} style={{margin:0}}><div className={styles.titleBlock}><div className={styles.actions}><h1 className={styles.title} style={{fontSize:22,margin:0}}>{data.candidateName}</h1><StatusBadge status={data.status}/></div><p className={styles.subtitle}>{data.jobTitle} · {data.unit.name} · admissão prevista para {formatDate(data.hireDate)}</p></div><div className={styles.actions}><button className={styles.button} onClick={()=>action('resend-link')}><Send size={14}/>Reenviar link</button><button className={styles.button} onClick={()=>action('renew-link')}><RefreshCw size={14}/>Gerar novo</button><button className={styles.buttonDanger} onClick={()=>action('invalidate-link')}><ShieldX size={14}/>Invalidar</button></div></div></div></div>
 <div className={styles.module}><div className={styles.content}><div className={styles.tabs}>{tabs.map((t,i)=><button key={t} className={`${styles.tab} ${active===i?styles.tabActive:''}`} onClick={()=>setActive(i)}>{t}</button>)}</div>
 {active===0&&<div className={styles.grid2}><div className={styles.metricList}><section className={styles.card}><div className={styles.cardHeader}><h2 className={styles.cardTitle}>Progresso da admissão</h2><strong style={{color:'#0A6F66'}}>{data.progress}% concluído</strong></div><div className={styles.progress}><span style={{width:`${data.progress}%`}}/></div><div className={styles.metricList} style={{marginTop:20}}>{steps.map(([label,p])=><div className={styles.attention} key={label}><span className={styles.dot} style={{'--dot':data.progress>=p?'#1E8E5A':data.progress+20>=p?'#C77B0A':'#9DAEB0'} as React.CSSProperties}/><div><div className={styles.itemTitle}>{label}</div><div className={styles.itemMeta}>{data.progress>=p?'Concluído':'Aguardando etapa anterior'}</div></div></div>)}</div></section><section className={styles.card}><h2 className={styles.cardTitle} style={{marginBottom:15}}>Resumo da contratação</h2><div className={styles.summaryGrid}><Summary label="Cargo" value={data.jobTitle}/><Summary label="Departamento" value={data.department}/><Summary label="Unidade" value={data.unit.name}/><Summary label="Salário" value={data.salary?data.salary.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—'}/><Summary label="Jornada" value={data.workSchedule}/><Summary label="Contrato" value={data.contractType}/></div></section></div><div className={styles.metricList}><section className={styles.card} style={{background:'#FFF9EE',borderColor:'#F0D9A8'}}><div className={styles.summaryLabel} style={{color:'#8A5A06'}}>Próxima ação necessária</div><h3 className={styles.itemTitle} style={{marginTop:8}}>{data.status==='CORRECTION_REQUESTED'?'Aguardando reenvio do candidato':data.status==='ERPNEXT_ERROR'?'Reprocessar integração':data.status==='COMPLETED'?'Processo concluído':'Acompanhar a etapa atual'}</h3><p className={styles.itemMeta}>Última atividade em {formatDateTime(data.lastActivityAt)}.</p></section><section className={styles.card}><h2 className={styles.cardTitle}>Link do candidato</h2><div className={`${styles.input} ${styles.mono}`} style={{height:'auto',padding:10,margin:'10px 0'}}>Token protegido · expira em {formatDate(data.tokens[0]?.expiresAt)}</div><button className={styles.button} onClick={()=>action('renew-link')}><Copy size={14}/>Gerar e copiar novo link</button></section></div></div>}
 {active===4&&<section className={styles.cardFlush}><div className={styles.cardHeader} style={{padding:'16px 18px',margin:0}}><h2 className={styles.cardTitle}>Documentos enviados</h2></div>{data.documents.map(d=><div className={styles.attention} style={{padding:'13px 18px'}} key={d.id}><div style={{flex:1}}><div className={styles.itemTitle}>{d.type.name}</div><div className={styles.itemMeta}>Versão {d.version} · {d.uploadedAt?`enviado em ${formatDateTime(d.uploadedAt)}`:'aguardando envio'}{d.rejectionReason?` · ${d.rejectionReason}`:''}</div></div><StatusBadge status={d.status}/>{d.uploadedAt&&<a className={styles.button} href={`/api/admissao-digital/documentos/${d.id}/arquivo`} target="_blank">Visualizar</a>}</div>)}</section>}
 {active===5&&<section className={styles.card}><div className={styles.cardHeader}><div><h2 className={styles.cardTitle}>Foto e validação facial</h2><p className={styles.itemMeta}>Comparação 1:1 entre a selfie e o documento de identidade aprovado.</p></div>{face&&<StatusBadge status={face.status}/>}</div><div className={styles.grid2} style={{marginTop:18}}><div><div className={styles.summaryLabel}>Selfie do candidato</div>{data.badgePhotos[0]?<img src={`/api/admissao-digital/admissoes/${id}/foto`} alt="Selfie do candidato" style={{width:'100%',height:300,objectFit:'contain',marginTop:8,border:'1px solid #E2E8E7',borderRadius:10,background:'#F6F8F8'}}/>:<div className={styles.empty}>Foto ainda não enviada.</div>}</div><div><div className={styles.summaryLabel}>Documento de referência</div>{identity?.uploadedAt&&identity.mimeType?.startsWith('image/')?<img src={`/api/admissao-digital/documentos/${identity.id}/arquivo`} alt="Documento de identidade" style={{width:'100%',height:300,objectFit:'contain',marginTop:8,border:'1px solid #E2E8E7',borderRadius:10,background:'#F6F8F8'}}/>:identity?.uploadedAt?<a className={styles.button} style={{marginTop:12}} href={`/api/admissao-digital/documentos/${identity.id}/arquivo`} target="_blank">Abrir documento em PDF</a>:<div className={styles.empty}>Documento ainda não enviado.</div>}</div></div><div className={styles.summaryGrid} style={{marginTop:18}}><Summary label="Provider" value={face?.provider||'—'}/><Summary label="Tentativas" value={String(face?.attempts||0)}/><Summary label="Similaridade" value={similarity==null?'Não calculada':`${(similarity*100).toFixed(1)}%`}/><Summary label="Resultado técnico" value={typeof faceMetadata.reason==='string'?faceMetadata.reason.replaceAll('_',' '):'—'}/></div>{face&&['MANUAL_REVIEW','ERROR','REJECTED'].includes(face.status)&&data.status==='FACE_VALIDATION_PENDING'&&<div className={styles.actions} style={{marginTop:18}}><button className={styles.buttonPrimary} onClick={()=>action('approve-face')}>Aprovar após revisão</button><button className={styles.buttonDanger} onClick={()=>action('request-face-retry')}>Solicitar nova captura</button></div>}<p className={styles.itemMeta} style={{marginTop:16}}>O score auxilia a revisão e não comprova prova de vida. A decisão manual fica registrada na auditoria.</p></section>}
 {active===7&&<section className={styles.card}><h2 className={styles.cardTitle}>Integração com o ERPNext</h2>{data.erpnextSyncs[0]?<div style={{marginTop:15}}><StatusBadge status={data.erpnextSyncs[0].status}/><p className={styles.itemMeta}>{data.erpnextSyncs[0].lastError||`${data.erpnextSyncs[0].attempts} tentativa(s)`}</p><button className={styles.buttonPrimary} onClick={()=>action('retry-erpnext')}>Reprocessar integração</button></div>:<div className={styles.empty}>A integração será criada depois da assinatura.</div>}</section>}
 {active===8&&<section className={styles.card}><h2 className={styles.cardTitle} style={{marginBottom:15}}>Histórico e auditoria</h2>{data.auditLogs.map(h=><div className={styles.attention} key={h.id}><span className={styles.dot}/><div><div className={styles.itemTitle}>{h.action.replaceAll('_',' ')}</div><div className={styles.itemMeta}>{formatDateTime(h.createdAt)} · {h.actorName||h.actorType}</div></div></div>)}</section>}
 {![0,4,5,7,8].includes(active)&&<section className={styles.card}><h2 className={styles.cardTitle}>{tabs[active]}</h2><div className={styles.empty}>Os dados desta área são exibidos de forma protegida conforme a permissão do usuário.</div></section>}
 </div></div>{toast&&<div className={styles.toast}>{toast}</div>}</>
}
function Summary({label,value}:{label:string;value?:string|null}){return <div><div className={styles.summaryLabel}>{label}</div><div className={styles.summaryValue}>{value||'—'}</div></div>}
