'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Header } from '@/components/layout/Header'
import { Check, Copy, ExternalLink } from 'lucide-react'
import styles from './Admission.module.css'
import { AdmissionTitle } from './shared'

type Meta={units:{id:string;name:string}[];candidates:{id:string;nome:string;email?:string;telefone?:string;vagaId:string;vaga:{cargo:string;unidadeId?:string}}[];vacancies:{id:string;titulo:string;cargo:string;setor?:string;unidadeId?:string;salarioMin?:number;horarioTrabalho?:string;cargaHoraria?:string;tipoContrato?:string}[];users:{id:string;name:string}[];documentTypes:{id:string;name:string;required:boolean}[]}
const steps=['Candidato','Vaga e unidade','Dados da contratação','Documentos necessários','Revisão']

export function AdmissionNew(){
 const router=useRouter(),[meta,setMeta]=useState<Meta|null>(null),[step,setStep]=useState(1),[saving,setSaving]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{publicUrl:string;expiresAt:string;admission:{id:string;protocol:string}}|null>(null)
 const [form,setForm]=useState({candidateId:'',candidateName:'',candidateEmail:'',candidatePhone:'',vacancyId:'',unitId:'',jobTitle:'',department:'',hireDate:'',salary:'',hazardPayPercentage:'',workSchedule:'',breakSchedule:'',weeklyHours:'44',contractType:'CLT - prazo indeterminado',experienceDays:'90',contractEndDate:'',ownerId:'',validityDays:'7'})
 useEffect(()=>{fetch('/api/admissao-digital/meta').then(r=>r.json()).then(setMeta)},[])
 const candidate=useMemo(()=>meta?.candidates.find(c=>c.id===form.candidateId),[meta,form.candidateId]);const vacancy=useMemo(()=>meta?.vacancies.find(v=>v.id===form.vacancyId),[meta,form.vacancyId])
 function change(name:string,value:string){setForm(f=>({...f,[name]:value}))}
 function chooseCandidate(id:string){const c=meta?.candidates.find(x=>x.id===id);setForm(f=>({...f,candidateId:id,candidateName:c?.nome||'',candidateEmail:c?.email||'',candidatePhone:c?.telefone||'',vacancyId:c?.vagaId||f.vacancyId,jobTitle:c?.vaga.cargo||f.jobTitle,unitId:c?.vaga.unidadeId||f.unitId}))}
 function chooseVacancy(id:string){const v=meta?.vacancies.find(x=>x.id===id);setForm(f=>({...f,vacancyId:id,unitId:v?.unidadeId||f.unitId,jobTitle:v?.cargo||'',department:v?.setor||'',salary:v?.salarioMin?String(v.salarioMin):f.salary,workSchedule:v?.horarioTrabalho||'',weeklyHours:v?.cargaHoraria?.replace(/\D/g,'')||f.weeklyHours,contractType:v?.tipoContrato||f.contractType}))}
 async function submit(e:FormEvent){e.preventDefault();if(step<5){setStep(s=>s+1);return}setSaving(true);setError('');try{const payload={...form,salary:form.salary?Number(form.salary):undefined,hazardPayPercentage:form.hazardPayPercentage?Number(form.hazardPayPercentage):undefined,weeklyHours:form.weeklyHours?Number(form.weeklyHours):undefined,experienceDays:form.experienceDays?Number(form.experienceDays):undefined,validityDays:Number(form.validityDays),contractEndDate:form.contractEndDate||undefined,ownerId:form.ownerId||undefined,candidateId:form.candidateId||undefined,vacancyId:form.vacancyId||undefined};const r=await fetch('/api/admissao-digital/admissoes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Não foi possível criar a admissão.');setResult(j)}catch(err){setError(err instanceof Error?err.message:'Erro inesperado.')}finally{setSaving(false)}}
 if(result)return <><Header title="Nova admissão"/><div className={styles.module}><div className={styles.content} style={{maxWidth:680}}><section className={styles.card} style={{textAlign:'center',padding:36}}><div style={{width:52,height:52,borderRadius:'50%',background:'#E6F4EC',color:'#1E8E5A',display:'grid',placeItems:'center',margin:'0 auto 16px'}}><Check size={25}/></div><h1 className={styles.title} style={{fontSize:20}}>Admissão criada com sucesso</h1><p className={styles.subtitle} style={{margin:'0 auto 20px'}}>O link individual foi gerado e é válido até {new Date(result.expiresAt).toLocaleDateString('pt-BR')}.</p><div className={`${styles.input} ${styles.mono}`} style={{height:'auto',padding:12,wordBreak:'break-all',marginBottom:12}}>{result.publicUrl}</div><div className={styles.actions} style={{justifyContent:'center'}}><button className={styles.buttonPrimary} onClick={()=>navigator.clipboard.writeText(result.publicUrl)}><Copy size={14}/>Copiar link</button><a className={styles.button} href={result.publicUrl} target="_blank"><ExternalLink size={14}/>Abrir portal</a><button className={styles.button} onClick={()=>router.push(`/admissao-digital/admissoes/${result.admission.id}`)}>Abrir admissão</button></div></section></div></div></>
 return <><Header title="Nova admissão" subtitle="Admissão Digital"/><div className={styles.module}><div className={styles.content} style={{maxWidth:860}}><AdmissionTitle title="Nova admissão" subtitle="Os dados definidos aqui não poderão ser alterados pelo candidato."/><div className={styles.stepper}>{steps.map((label,i)=><div key={label} className={`${styles.step} ${i+1<step?styles.stepDone:i+1===step?styles.stepCurrent:''}`}><span className={styles.stepCircle}>{i+1<step?<Check size={12}/>:i+1}</span>{i<steps.length-1&&<span className={styles.stepLine}/>}</div>)}</div><form onSubmit={submit} className={styles.card}>
  {step===1&&<><h2 className={styles.cardTitle}>Quem será admitido?</h2><p className={styles.subtitle} style={{margin:'4px 0 18px'}}>Selecione um candidato aprovado no Controle de Candidatos ou preencha manualmente.</p><div className={styles.formGrid}><Field label="Candidato aprovado"><select className={styles.select} value={form.candidateId} onChange={e=>chooseCandidate(e.target.value)}><option value="">Cadastro manual</option>{meta?.candidates.map(c=><option key={c.id} value={c.id}>{c.nome} · {c.vaga.cargo}</option>)}</select></Field><Field label="Nome completo *"><input required className={styles.input} value={form.candidateName} onChange={e=>change('candidateName',e.target.value)}/></Field><Field label="E-mail"><input type="email" className={styles.input} value={form.candidateEmail} onChange={e=>change('candidateEmail',e.target.value)}/></Field><Field label="Telefone"><input inputMode="tel" className={styles.input} value={form.candidatePhone} onChange={e=>change('candidatePhone',e.target.value)}/></Field></div></>}
  {step===2&&<><h2 className={styles.cardTitle}>Vaga e unidade</h2><p className={styles.subtitle} style={{margin:'4px 0 18px'}}>Vincule a admissão à vaga correspondente.</p><div className={styles.formGrid}><Field label="Vaga"><select className={styles.select} value={form.vacancyId} onChange={e=>chooseVacancy(e.target.value)}><option value="">Sem vaga vinculada</option>{meta?.vacancies.map(v=><option key={v.id} value={v.id}>{v.titulo} · {v.cargo}</option>)}</select></Field><Field label="Unidade *"><select required className={styles.select} value={form.unitId} onChange={e=>change('unitId',e.target.value)}><option value="">Selecione</option>{meta?.units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Cargo *"><input required className={styles.input} value={form.jobTitle} onChange={e=>change('jobTitle',e.target.value)}/></Field><Field label="Departamento"><input className={styles.input} value={form.department} onChange={e=>change('department',e.target.value)}/></Field></div></>}
  {step===3&&<><h2 className={styles.cardTitle}>Dados da contratação</h2><p className={styles.subtitle} style={{margin:'4px 0 18px'}}>Estas informações aparecem ao candidato somente para leitura.</p><div className={styles.formGrid}><Field label="Data prevista de admissão *"><input required type="date" className={styles.input} value={form.hireDate} onChange={e=>change('hireDate',e.target.value)}/></Field><Field label="Salário"><input inputMode="decimal" className={styles.input} value={form.salary} onChange={e=>change('salary',e.target.value)}/></Field><Field label="Insalubridade (%)"><input type="number" min="0" max="100" className={styles.input} value={form.hazardPayPercentage} onChange={e=>change('hazardPayPercentage',e.target.value)}/></Field><Field label="Horário"><input className={styles.input} value={form.workSchedule} onChange={e=>change('workSchedule',e.target.value)}/></Field><Field label="Intervalo"><input className={styles.input} value={form.breakSchedule} onChange={e=>change('breakSchedule',e.target.value)}/></Field><Field label="Carga horária semanal"><input type="number" className={styles.input} value={form.weeklyHours} onChange={e=>change('weeklyHours',e.target.value)}/></Field><Field label="Tipo de contrato *"><input required className={styles.input} value={form.contractType} onChange={e=>change('contractType',e.target.value)}/></Field><Field label="Experiência (dias)"><input type="number" className={styles.input} value={form.experienceDays} onChange={e=>change('experienceDays',e.target.value)}/></Field><Field label="Responsável pelo RH"><select className={styles.select} value={form.ownerId} onChange={e=>change('ownerId',e.target.value)}><option value="">Usuário atual</option>{meta?.users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Validade do link"><select className={styles.select} value={form.validityDays} onChange={e=>change('validityDays',e.target.value)}><option value="3">3 dias</option><option value="7">7 dias</option><option value="14">14 dias</option><option value="30">30 dias</option></select></Field></div></>}
  {step===4&&<><h2 className={styles.cardTitle}>Documentos necessários</h2><p className={styles.subtitle} style={{margin:'4px 0 18px'}}>Checklist configurado para esta contratação.</p><div className={styles.metricList}>{meta?.documentTypes.map(d=><label className={styles.docRow} key={d.id}><input type="checkbox" defaultChecked/> <strong>{d.name}</strong><span className={styles.itemMeta}> · {d.required?'Obrigatório':'Opcional'}</span></label>)}</div></>}
  {step===5&&<><h2 className={styles.cardTitle}>Revise antes de enviar</h2><p className={styles.subtitle} style={{margin:'4px 0 18px'}}>Ao confirmar, o sistema gera um link individual seguro.</p><div className={styles.summaryGrid}><Summary label="Candidato" value={form.candidateName}/><Summary label="Cargo" value={form.jobTitle}/><Summary label="Unidade" value={meta?.units.find(u=>u.id===form.unitId)?.name||'—'}/><Summary label="Admissão" value={form.hireDate?new Date(`${form.hireDate}T12:00:00`).toLocaleDateString('pt-BR'):'—'}/><Summary label="Contrato" value={form.contractType}/><Summary label="Link" value={`${form.validityDays} dias`}/></div></>}
  {error&&<p className={styles.error}>{error}</p>}<div className={styles.actions} style={{justifyContent:'space-between',marginTop:24}}><button type="button" className={styles.button} onClick={()=>step===1?router.back():setStep(s=>s-1)}>{step===1?'Cancelar':'Voltar'}</button><button className={styles.buttonPrimary} disabled={saving}>{saving?'Criando…':step===5?'Criar admissão e gerar link':'Continuar'}</button></div>
 </form></div></div></>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className={styles.field}><label className={styles.label}>{label}</label>{children}</div>}
function Summary({label,value}:{label:string;value:string}){return <div><div className={styles.summaryLabel}>{label}</div><div className={styles.summaryValue}>{value}</div></div>}
