'use client'

import { useCallback, useEffect, useState } from 'react'
import { Header } from '@/components/layout/Header'
import { Copy, Download, MapPin, RefreshCw, ShieldX, Send } from 'lucide-react'
import styles from './Admission.module.css'
import { ErrorState, formatDate, formatDateTime, StatusBadge } from './shared'

type AdmissionField={section:string;key:string;value:unknown}
type Dependent={id:string;name:string;cpfMasked?:string;birthDate:string;relationship:string;irrfDependent:boolean;childUnder14:boolean}
type Transport={requested:boolean;refusalReason?:string;declarationVersion:string;declarationAcceptedAt?:string;routes:{id:string;type:string;line:string;outbound:number;returnValue:number}[]}
type GeneratedDocument={id:string;status:string;templateVersion:number;generatedAt?:string;signedAt?:string;validationCode?:string;originalHash?:string;finalHash?:string;template:{key:string;name:string}}
type SignatureEnvelope={id:string;documentId:string;provider:string;signerName:string;signerEmail?:string;status:string;transactionId?:string;signedAt?:string;signedIp?:string;signedUserAgent?:string;latitude?:number;longitude?:number;locationAccuracy?:number;events:{id:string;type:string;hash?:string;createdAt:string}[]}
type Detail={id:string;protocol:string;candidateName:string;candidateEmail?:string;candidatePhone?:string;jobTitle:string;department?:string;hireDate:string;salary?:number;hazardPayPercentage?:number;workSchedule?:string;breakSchedule?:string;weeklyHours?:number;monthlyHours?:number;contractType:string;experienceDays?:number;contractEndDate?:string;status:string;progress:number;lastActivityAt:string;unit:{name:string};vacancy?:{titulo:string};owner?:{name:string};tokens:{expiresAt:string;revokedAt?:string}[];documents:{id:string;status:string;rejectionReason?:string;version:number;uploadedAt?:string;mimeType?:string;type:{key:string;name:string}}[];badgePhotos:{id:string;confirmedAt?:string}[];faceVerifications:{id:string;provider:string;status:string;attempts:number;resultMetadata?:Record<string,unknown>;completedAt?:string;capturedAt?:string}[];dependents:Dependent[];transport?:Transport;fields:AdmissionField[];generatedDocuments:GeneratedDocument[];signatureEnvelopes:SignatureEnvelope[];erpnextSyncs:{status:string;attempts:number;lastError?:string;lastSyncedAt?:string}[];auditLogs:{id:string;action:string;actorName?:string;actorType:string;createdAt:string}[]}
const tabs=['Visão geral','Dados pessoais','Dependentes','Vale-transporte','Documentos','Foto e validação facial','Contratos e assinatura','ERPNext','Histórico']

export function AdmissionDetail({id}:{id:string}){
 const [data,setData]=useState<Detail|null>(null),[active,setActive]=useState(0),[error,setError]=useState(''),[toast,setToast]=useState('')
 const load=useCallback(async()=>{try{const r=await fetch(`/api/admissao-digital/admissoes/${id}`);if(!r.ok)throw new Error();setData(await r.json())}catch{setError('Não foi possível carregar a admissão.')}},[id]);useEffect(()=>{load()},[load])
 async function action(name:string,body:Record<string,unknown>={}){if(['invalidate-link','cancel','approve-face','request-face-retry'].includes(name)&&!confirm('Confirma esta ação? Ela será registrada na auditoria.'))return;const r=await fetch(`/api/admissao-digital/admissoes/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:name,...body})});const j=await r.json();if(!r.ok){setToast(j.error||'Ação não concluída.');return}if(name==='retry-erpnext'){const processResponse=await fetch('/api/admissao-digital/erpnext/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({admissionId:id})});const processResult=await processResponse.json();if(!processResponse.ok){setToast(processResult.error||'Não foi possível processar a integração.')}else setToast(processResult.results?.[0]?.status==='SUCCESS'?'Integração concluída.':'A integração falhou. Consulte o erro na aba ERPNext.')}else if(j.publicUrl){await navigator.clipboard.writeText(j.publicUrl);setToast('Novo link copiado.')}else setToast('Ação concluída.');await load();setTimeout(()=>setToast(''),5000)}
 if(error)return <><Header title="Admissão Digital"/><div className={styles.module}><ErrorState message={error} retry={load}/></div></>
 if(!data)return <><Header title="Admissão Digital"/><div className={styles.module}><div className={styles.skeleton}/></div></>
 const steps=[['Dados pessoais',18],['Documentos',55],['Foto e validação facial',74],['Documentos admissionais',82],['Assinatura',94],['Integração ERPNext',98],['Conclusão',100]] as const
 const face=data.faceVerifications[0],identity=data.documents.find(document=>document.type.key==='rg_frente'),faceMetadata=face?.resultMetadata||{},similarity=typeof faceMetadata.similarity==='number'?faceMetadata.similarity:null
 return <><Header title={data.candidateName} subtitle={data.protocol}/><div className={styles.detailHeader}><div className={styles.content}><div className={styles.titleRow} style={{margin:0}}><div className={styles.titleBlock}><div className={styles.actions}><h1 className={styles.title} style={{fontSize:22,margin:0}}>{data.candidateName}</h1><StatusBadge status={data.status}/></div><p className={styles.subtitle}>{data.jobTitle} · {data.unit.name} · admissão prevista para {formatDate(data.hireDate)}</p></div><div className={styles.actions}><button className={styles.button} onClick={()=>action('resend-link')}><Send size={14}/>Reenviar link</button><button className={styles.button} onClick={()=>action('renew-link')}><RefreshCw size={14}/>Gerar novo</button><button className={styles.buttonDanger} onClick={()=>action('invalidate-link')}><ShieldX size={14}/>Invalidar</button></div></div></div></div>
 <div className={styles.module}><div className={styles.content}><div className={styles.tabs}>{tabs.map((t,i)=><button key={t} className={`${styles.tab} ${active===i?styles.tabActive:''}`} onClick={()=>setActive(i)}>{t}</button>)}</div>
 {active===0&&<div className={styles.grid2}><div className={styles.metricList}><section className={styles.card}><div className={styles.cardHeader}><h2 className={styles.cardTitle}>Progresso da admissão</h2><strong style={{color:'#0A6F66'}}>{data.progress}% concluído</strong></div><div className={styles.progress}><span style={{width:`${data.progress}%`}}/></div><div className={styles.metricList} style={{marginTop:20}}>{steps.map(([label,p])=><div className={styles.attention} key={label}><span className={styles.dot} style={{'--dot':data.progress>=p?'#1E8E5A':data.progress+20>=p?'#C77B0A':'#9DAEB0'} as React.CSSProperties}/><div><div className={styles.itemTitle}>{label}</div><div className={styles.itemMeta}>{data.progress>=p?'Concluído':'Aguardando etapa anterior'}</div></div></div>)}</div></section><section className={styles.card}><h2 className={styles.cardTitle} style={{marginBottom:15}}>Resumo da contratação</h2><div className={styles.summaryGrid}><Summary label="Cargo" value={data.jobTitle}/><Summary label="Departamento" value={data.department}/><Summary label="Unidade" value={data.unit.name}/><Summary label="Salário" value={data.salary?data.salary.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—'}/><Summary label="Jornada" value={data.workSchedule}/><Summary label="Contrato" value={data.contractType}/></div></section></div><div className={styles.metricList}><section className={styles.card} style={{background:'#FFF9EE',borderColor:'#F0D9A8'}}><div className={styles.summaryLabel} style={{color:'#8A5A06'}}>Próxima ação necessária</div><h3 className={styles.itemTitle} style={{marginTop:8}}>{data.status==='CORRECTION_REQUESTED'?'Aguardando reenvio do candidato':data.status==='ERPNEXT_ERROR'?'Reprocessar integração':data.status==='COMPLETED'?'Processo concluído':'Acompanhar a etapa atual'}</h3><p className={styles.itemMeta}>Última atividade em {formatDateTime(data.lastActivityAt)}.</p></section><section className={styles.card}><h2 className={styles.cardTitle}>Link do candidato</h2><div className={`${styles.input} ${styles.mono}`} style={{height:'auto',padding:10,margin:'10px 0'}}>Token protegido · expira em {formatDate(data.tokens[0]?.expiresAt)}</div><button className={styles.button} onClick={()=>action('renew-link')}><Copy size={14}/>Gerar e copiar novo link</button></section></div></div>}
 {active===1&&<PersonalDataPanel data={data}/>} 
 {active===2&&<DependentsPanel dependents={data.dependents}/>} 
 {active===3&&<TransportPanel transport={data.transport}/>} 
 {active===4&&<section className={styles.cardFlush}><div className={styles.cardHeader} style={{padding:'16px 18px',margin:0}}><h2 className={styles.cardTitle}>Documentos enviados</h2>{data.badgePhotos[0]?.confirmedAt&&<button className={styles.buttonDanger} onClick={()=>{const reason=prompt('Motivo para solicitar outra foto do crachá:');if(reason)action('request-badge-retry',{reason})}}>Solicitar nova foto do crachá</button>}</div>{data.documents.map(d=><div className={styles.attention} style={{padding:'13px 18px'}} key={d.id}><div style={{flex:1}}><div className={styles.itemTitle}>{d.type.name}</div><div className={styles.itemMeta}>Versão {d.version} · {d.uploadedAt?`enviado em ${formatDateTime(d.uploadedAt)}`:'aguardando envio'}{d.rejectionReason?` · ${d.rejectionReason}`:''}</div></div><StatusBadge status={d.status}/>{d.uploadedAt&&<a className={styles.button} href={`/api/admissao-digital/documentos/${d.id}/arquivo`} target="_blank">Visualizar</a>}</div>)}</section>}
 {active===5&&<FacePanel id={id} data={data} face={face} identity={identity} faceMetadata={faceMetadata} similarity={similarity} action={action}/>}
 {active===6&&<ContractsPanel id={id} data={data}/>} 
 {active===7&&<section className={styles.card}><h2 className={styles.cardTitle}>Integração com o ERPNext</h2>{data.erpnextSyncs[0]?<div style={{marginTop:15}}><StatusBadge status={data.erpnextSyncs[0].status}/><p className={styles.itemMeta}>{data.erpnextSyncs[0].lastError||`${data.erpnextSyncs[0].attempts} tentativa(s)`}</p><button className={styles.buttonPrimary} onClick={()=>action('retry-erpnext')}>Reprocessar integração</button></div>:<div className={styles.empty}>A integração será criada depois da assinatura.</div>}</section>}
 {active===8&&<section className={styles.card}><h2 className={styles.cardTitle} style={{marginBottom:15}}>Histórico e auditoria</h2>{data.auditLogs.map(h=><div className={styles.attention} key={h.id}><span className={styles.dot}/><div><div className={styles.itemTitle}>{h.action.replaceAll('_',' ')}</div><div className={styles.itemMeta}>{formatDateTime(h.createdAt)} · {h.actorName||h.actorType}</div></div></div>)}</section>}
 </div></div>{toast&&<div className={styles.toast}>{toast}</div>}</>
}

const fieldGroups = [
 {title:'Identificação e contato',keys:[['name','Nome completo'],['birthDate','Data de nascimento'],['gender','Gênero'],['phone','Telefone'],['messagePhone','Telefone de recado'],['email','E-mail'],['cpf','CPF'],['rg','RG'],['rgIssuedAt','Expedição do RG'],['rgIssuer','Órgão emissor'],['pis','PIS'],['birthCity','Cidade de nascimento'],['ethnicity','Etnia'],['disability','Pessoa com deficiência'],['disabilityDetails','Deficiência'],['fatherName','Nome do pai'],['motherName','Nome da mãe'],['education','Grau de instrução'],['maritalStatus','Estado civil']]},
 {title:'Endereço',keys:[['zipCode','CEP'],['street','Logradouro'],['number','Número'],['complement','Complemento'],['district','Bairro'],['city','Cidade'],['state','UF']]},
 {title:'Dados bancários',keys:[['bank','Banco'],['agency','Agência'],['account','Conta'],['accountDigit','Dígito'],['accountType','Tipo de conta']]},
] as const

function displayValue(value:unknown){if(value==null||value==='')return '—';if(typeof value==='boolean')return value?'Sim':'Não';const labels:Record<string,string>={Female:'Feminino',Male:'Masculino',Other:'Outro','Prefer not to say':'Prefiro não informar'};return labels[String(value)]||String(value)}

function PersonalDataPanel({data}:{data:Detail}){
 const values=Object.fromEntries(data.fields.map(field=>[field.key,field.value]))
 return <div className={styles.metricList}>
  {fieldGroups.map(group=><section className={styles.card} key={group.title}><h2 className={styles.cardTitle} style={{marginBottom:16}}>{group.title}</h2><div className={styles.summaryGrid}>{group.keys.map(([key,label])=><Summary key={key} label={label} value={displayValue(values[key])}/>)}</div></section>)}
  <section className={styles.card}><h2 className={styles.cardTitle} style={{marginBottom:16}}>Dados da contratação</h2><div className={styles.summaryGrid}><Summary label="Vaga" value={data.vacancy?.titulo}/><Summary label="Cargo" value={data.jobTitle}/><Summary label="Departamento" value={data.department}/><Summary label="Unidade" value={data.unit.name}/><Summary label="Admissão" value={formatDate(data.hireDate)}/><Summary label="Salário" value={data.salary?.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}/><Summary label="Insalubridade" value={data.hazardPayPercentage==null?'—':`${data.hazardPayPercentage}%`}/><Summary label="Jornada" value={data.workSchedule}/><Summary label="Intervalo" value={data.breakSchedule}/><Summary label="Carga horária" value={data.monthlyHours?`${data.monthlyHours} horas mensais`:data.weeklyHours?`${data.weeklyHours} horas semanais`:'—'}/><Summary label="Tipo de contrato" value={data.contractType}/><Summary label="Experiência" value={data.experienceDays?`${data.experienceDays} dias`:'—'}/><Summary label="Término previsto" value={formatDate(data.contractEndDate)}/></div></section>
 </div>
}

function DependentsPanel({dependents}:{dependents:Dependent[]}){
 return <section className={styles.card}><div className={styles.cardHeader}><h2 className={styles.cardTitle}>Dependentes</h2><span className={styles.itemMeta}>{dependents.length} cadastrado(s)</span></div>{dependents.length?dependents.map(dependent=><div className={styles.docRow} key={dependent.id}><div className={styles.summaryGrid}><Summary label="Nome" value={dependent.name}/><Summary label="CPF" value={dependent.cpfMasked}/><Summary label="Nascimento" value={formatDate(dependent.birthDate)}/><Summary label="Relação" value={dependent.relationship}/><Summary label="Dependente IRRF" value={dependent.irrfDependent?'Sim':'Não'}/><Summary label="Menor de 14 anos" value={dependent.childUnder14?'Sim':'Não'}/></div></div>):<div className={styles.empty}>Nenhum dependente informado.</div>}</section>
}

function TransportPanel({transport}:{transport?:Transport}){
 if(!transport)return <section className={styles.card}><h2 className={styles.cardTitle}>Vale-transporte</h2><div className={styles.empty}>Informações ainda não preenchidas.</div></section>
 const total=transport.routes.reduce((sum,route)=>sum+route.outbound+route.returnValue,0)
 return <section className={styles.card}><div className={styles.cardHeader}><div><h2 className={styles.cardTitle}>Vale-transporte</h2><p className={styles.itemMeta}>Declaração versão {transport.declarationVersion}</p></div><StatusBadge status={transport.requested?'APPROVED':'REJECTED'} label={transport.requested?'Solicitado':'Não solicitado'}/></div><div className={styles.summaryGrid}><Summary label="Aceite da declaração" value={formatDateTime(transport.declarationAcceptedAt)}/>{!transport.requested&&<Summary label="Motivo" value={transport.refusalReason}/>} {transport.requested&&<Summary label="Total diário" value={total.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}/>}</div>{transport.requested&&<div style={{marginTop:18}}>{transport.routes.map(route=><div className={styles.docRow} key={route.id}><div className={styles.summaryGrid}><Summary label="Tipo" value={route.type}/><Summary label="Linha/trecho" value={route.line}/><Summary label="Ida" value={route.outbound.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}/><Summary label="Volta" value={route.returnValue.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}/></div></div>)}</div>}</section>
}

function ContractsPanel({id,data}:{id:string;data:Detail}){
 return <div className={styles.metricList}><section className={styles.card}><div className={styles.cardHeader}><div><h2 className={styles.cardTitle}>Contratos e documentos admissionais</h2><p className={styles.itemMeta}>Os PDFs são gerados com os dados da contratação e do formulário do candidato.</p></div></div>{data.generatedDocuments.length?data.generatedDocuments.map(document=>{const envelope=data.signatureEnvelopes.find(item=>item.documentId===document.id);return <div className={styles.docRow} key={document.id}><div className={styles.cardHeader} style={{margin:0}}><div><div className={styles.itemTitle}>{document.template.name}</div><div className={styles.itemMeta}>Versão {document.templateVersion} · validação {document.validationCode||'—'}</div></div><StatusBadge status={document.status}/></div><div className={styles.actions} style={{marginTop:12}}><a className={styles.buttonPrimary} href={`/api/admissao-digital/admissoes/${id}/documentos-gerados/${document.id}/arquivo`}><Download size={14}/>{document.status==='SIGNED'?'Baixar PDF assinado':'Baixar PDF'}</a></div>{envelope?.signedAt&&<div className={styles.summaryGrid} style={{marginTop:16}}><Summary label="Signatário" value={envelope.signerName}/><Summary label="Assinado em" value={formatDateTime(envelope.signedAt)}/><Summary label="IP" value={envelope.signedIp}/><Summary label="Provider" value={envelope.provider}/><Summary label="Transação" value={envelope.transactionId}/><Summary label="Hash final" value={document.finalHash}/></div>}{envelope?.latitude!=null&&envelope.longitude!=null&&<div className={styles.itemMeta} style={{marginTop:12}}><MapPin size={13} style={{verticalAlign:'middle'}}/> Localização consentida: {envelope.latitude.toFixed(6)}, {envelope.longitude.toFixed(6)} · precisão aproximada {Math.round(envelope.locationAccuracy||0)} m</div>}</div>}):<div className={styles.empty}>Os documentos serão gerados após a revisão final do candidato.</div>}</section></div>
}

function FacePanel({id,data,face,identity,faceMetadata,similarity,action}:{id:string;data:Detail;face:Detail['faceVerifications'][number]|undefined;identity:Detail['documents'][number]|undefined;faceMetadata:Record<string,unknown>;similarity:number|null;action:(name:string,body?:Record<string,unknown>)=>Promise<void>}){
 return <section className={styles.card}>
  <div className={styles.cardHeader}><div><h2 className={styles.cardTitle}>Foto e validação facial</h2><p className={styles.itemMeta}>Comparação 1:1 entre a captura facial e o documento de identidade aprovado.</p></div>{face&&<StatusBadge status={face.status}/>}</div>
  <div className={styles.grid2} style={{marginTop:18}}>
   <div><div className={styles.summaryLabel}>Captura facial do candidato</div>{face?.capturedAt?<img src={`/api/admissao-digital/admissoes/${id}/validacao-facial/foto`} alt="Captura facial do candidato" style={{width:'100%',height:300,objectFit:'contain',marginTop:8,border:'1px solid #E2E8E7',borderRadius:10,background:'#F6F8F8'}}/>:<div className={styles.empty}>Captura facial ainda não realizada.</div>}</div>
   <div><div className={styles.summaryLabel}>Documento de referência</div>{identity?.uploadedAt&&identity.mimeType?.startsWith('image/')?<img src={`/api/admissao-digital/documentos/${identity.id}/arquivo`} alt="Documento de identidade" style={{width:'100%',height:300,objectFit:'contain',marginTop:8,border:'1px solid #E2E8E7',borderRadius:10,background:'#F6F8F8'}}/>:identity?.uploadedAt?<div style={{marginTop:8}}><object data={`/api/admissao-digital/documentos/${identity.id}/arquivo#toolbar=0&navpanes=0`} type="application/pdf" aria-label="Documento de identidade em PDF" style={{display:'block',width:'100%',height:300,border:'1px solid #E2E8E7',borderRadius:10,background:'#F6F8F8'}}><div className={styles.empty}>Este navegador não conseguiu exibir o PDF.</div></object><a className={styles.button} style={{marginTop:8,display:'inline-flex'}} href={`/api/admissao-digital/documentos/${identity.id}/arquivo`} target="_blank" rel="noopener noreferrer">Abrir PDF em outra aba</a></div>:<div className={styles.empty}>Documento ainda não enviado.</div>}</div>
  </div>
  <div className={styles.summaryGrid} style={{marginTop:18}}><Summary label="Provider" value={face?.provider||'—'}/><Summary label="Tentativas" value={String(face?.attempts||0)}/><Summary label="Similaridade" value={similarity==null?'Não calculada':`${(similarity*100).toFixed(1)}%`}/><Summary label="Resultado técnico" value={typeof faceMetadata.reason==='string'?faceMetadata.reason.replaceAll('_',' '):'—'}/></div>
  {face&&['MANUAL_REVIEW','ERROR','REJECTED'].includes(face.status)&&data.status==='FACE_VALIDATION_PENDING'&&<div className={styles.actions} style={{marginTop:18}}><button className={styles.buttonPrimary} onClick={()=>action('approve-face')}>Aprovar após revisão</button><button className={styles.buttonDanger} onClick={()=>action('request-face-retry')}>Solicitar nova captura</button></div>}
  <p className={styles.itemMeta} style={{marginTop:16}}>O score auxilia a revisão e não comprova prova de vida. A decisão manual fica registrada na auditoria.</p>
 </section>
}
function Summary({label,value}:{label:string;value?:string|null}){return <div><div className={styles.summaryLabel}>{label}</div><div className={styles.summaryValue}>{value||'—'}</div></div>}
