'use client'

import {FormEvent,useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {useRouter} from 'next/navigation'
import {Camera,Check,ChevronLeft,ChevronRight,FileUp,Plus,Trash2,WifiOff} from 'lucide-react'
import styles from './Admission.module.css'
import {StatusBadge} from './shared'
import {formatAccount,formatAccountDigit,formatAgency,formatCep,formatCpf,formatPhone,formatPis,formatRg,onlyDigits} from '@/lib/admission/fieldFormatters'

type PortalData={protocol:string;candidateName:string;status:string;currentStep:string;progress:number;expiresAt:string;locked:{jobTitle:string;department?:string;unit:string;hireDate:string;contractType:string;workSchedule?:string};fields:Record<string,any>;dependents:any[];transport:any;documents:any[];badgePhoto:any;faceVerification:any;generatedDocuments:any[];signatures:any[]}
const order=['inicio','dados','endereco','dados-bancarios','dependentes','vale-transporte','documentos','foto','validacao-facial','revisao','assinatura','conclusao']
const routes:Record<string,string>={inicio:'',dados:'dados',endereco:'endereco','dados-bancarios':'dados-bancarios',dependentes:'dependentes','vale-transporte':'vale-transporte',documentos:'documentos',foto:'foto','validacao-facial':'validacao-facial',revisao:'revisao',assinatura:'assinatura',conclusao:'conclusao'}
const progress:Record<string,number>={inicio:4,dados:14,endereco:22,'dados-bancarios':30,dependentes:38,'vale-transporte':46,documentos:58,foto:68,'validacao-facial':76,revisao:84,assinatura:94,conclusao:100}
const EDUCATION_OPTIONS=['Não alfabetizado','Ensino Fundamental incompleto','Ensino Fundamental completo','Ensino Médio incompleto','Ensino Médio completo','Ensino Técnico incompleto','Ensino Técnico completo','Ensino Superior incompleto','Ensino Superior completo','Pós-graduação completa','Mestrado completo','Doutorado completo']
const MARITAL_STATUS_OPTIONS=['Solteiro(a)','Casado(a)','União estável','Separado(a)','Divorciado(a)','Viúvo(a)']
const ACCOUNT_TYPE_OPTIONS=['Conta corrente','Conta poupança','Conta salário','Conta de pagamento']
type PortalField={key:string;label:string;type?:string;inputMode?:'text'|'numeric'|'tel'|'email';format?:(value:unknown)=>string;maxLength?:number;options?:string[];placeholder?:string;required?:boolean;onChange?:(value:string)=>void}

export function CandidatePortal({token,step}:{token:string;step:string}){
 const router=useRouter(),current=order.includes(step)?step:'inicio',[data,setData]=useState<PortalData|null>(null),[form,setForm]=useState<Record<string,any>>({}),[dependents,setDependents]=useState<any[]>([]),[transport,setTransport]=useState<any>({requested:null,refusalReason:'',declarationAccepted:false,routes:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saved,setSaved]=useState(''),[offline,setOffline]=useState(false),[accepted,setAccepted]=useState(false),[photo,setPhoto]=useState<File|null>(null),[photoPreview,setPhotoPreview]=useState('');const dirty=useRef(false)
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`/api/admissao/${token}`,{cache:'no-store'}),j=await r.json().catch(()=>({error:'Link inválido ou indisponível.'}));if(!r.ok)throw Error(j.error);setData(j);setForm(j.fields||{});setDependents((j.dependents||[]).map((d:any)=>({...d,birthDate:d.birthDate?.slice(0,10),cpf:''})));setTransport(j.transport?{...j.transport,declarationAccepted:!!j.transport.declarationAcceptedAt}: {requested:null,refusalReason:'',declarationAccepted:false,routes:[]});setError('')}catch(e){setError(e instanceof Error?e.message:'Não foi possível abrir o portal.')}finally{setLoading(false)}},[token]);useEffect(()=>{load()},[load]);useEffect(()=>{const on=()=>setOffline(!navigator.onLine);on();addEventListener('online',on);addEventListener('offline',on);return()=>{removeEventListener('online',on);removeEventListener('offline',on)}},[])
 const section=useMemo(()=>current==='dados'?'personal':current==='endereco'?'address':current==='dados-bancarios'?'bank':null,[current])
 // saveFields lê o snapshot atual de `form`; reiniciar o debounce é intencional a cada alteração.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!dirty.current||!section)return;const id=setTimeout(()=>saveFields(section,false),850);return()=>clearTimeout(id)},[form,section])
 function url(next:string){return `/admissao/${token}${routes[next]?`/${routes[next]}`:''}`};function go(next:string){router.push(url(next))};function set(name:string,value:any){dirty.current=true;setSaved('Salvando…');setForm(f=>({...f,[name]:value}))}
 async function saveFields(sec:string,navigate=true){const keys:any={personal:['name','birthDate','phone','messagePhone','email','rg','rgIssuedAt','rgIssuer','cpf','pis','birthCity','ethnicity','disability','disabilityDetails','fatherName','motherName','education','maritalStatus'],address:['zipCode','street','number','complement','district','city','state'],bank:['bank','agency','account','accountDigit','accountType']};const fields=Object.fromEntries(keys[sec].map((k:string)=>[k,form[k]??'']));try{if(navigate)setError('');const r=await fetch(`/api/admissao/${token}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({section:sec,fields,nextStep:current,validate:navigate})});const j=await r.json();if(!r.ok){const firstInvalid=j.fields&&Object.keys(j.fields)[0];if(firstInvalid)requestAnimationFrame(()=>document.querySelector<HTMLElement>(`[name="${firstInvalid}"]`)?.focus());throw Error(j.error)}dirty.current=false;setSaved('Alterações salvas');setError('');if(navigate)go(current==='dados'?'endereco':current==='endereco'?'dados-bancarios':'dependentes')}catch(e){setSaved('');setError(e instanceof Error?e.message:'Não foi possível salvar.') }}
 async function saveDependents(){const r=await fetch(`/api/admissao/${token}/dependentes`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({dependents})}),j=await r.json();if(!r.ok){setError(j.error);return}go('vale-transporte')}
 async function saveTransport(){const r=await fetch(`/api/admissao/${token}/vale-transporte`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(transport)}),j=await r.json();if(!r.ok){setError(j.error);return}go('documentos')}
 async function uploadDoc(id:string,file?:File){if(!file)return;const fd=new FormData();fd.append('file',file);setSaved('Enviando…');const r=await fetch(`/api/admissao/${token}/documentos/${id}/upload`,{method:'POST',body:fd}),j=await r.json();if(!r.ok){setError(j.error);return}setSaved('Documento enviado');await load()}
 async function uploadPhoto(){if(!photo){setError('Capture ou selecione uma foto.');return}const fd=new FormData();fd.append('file',photo);const r=await fetch(`/api/admissao/${token}/foto`,{method:'POST',body:fd}),j=await r.json();if(!r.ok){setError(j.error);return}go('validacao-facial')}
 async function face(){const r=await fetch(`/api/admissao/${token}/validacao-facial`,{method:'POST'}),j=await r.json();if(!r.ok){setError(j.error);await load();return}if(j.status==='APPROVED'){go('revisao');return}await load();setError(j.requiresHumanReview?'Sua comparação facial foi encaminhada para revisão do RH. Você pode voltar pelo mesmo link mais tarde.':'Não conseguimos concluir a validação. Tente novamente.')}
 async function generateDocs(){const r=await fetch(`/api/admissao/${token}/documentos-gerados`,{method:'POST'}),j=await r.json();if(!r.ok){setError(j.error);return}await load();go('assinatura')}
 async function sign(){const r=await fetch(`/api/admissao/${token}/assinatura`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accepted})}),j=await r.json();if(!r.ok){setError(j.error);return}go('conclusao')}
 const index=order.indexOf(current),back=()=>index>0&&go(order[index-1]),next:Record<string,()=>void>={inicio:()=>go('dados'),dados:()=>saveFields('personal'),endereco:()=>saveFields('address'),'dados-bancarios':()=>saveFields('bank'),dependentes:saveDependents,'vale-transporte':saveTransport,documentos:()=>go('foto'),foto:uploadPhoto,'validacao-facial':face,revisao:generateDocs,assinatura:sign,conclusao:()=>{}}
 const waitingFaceReview=current==='validacao-facial'&&data?.faceVerification?.status==='MANUAL_REVIEW'
 if(loading)return <PortalFrame progress={6} saved=""><div className={styles.skeleton} style={{height:420}}/></PortalFrame>
 if(error&&!data)return <PortalFrame progress={0} saved=""><section className={styles.portalCard} style={{textAlign:'center'}}><h1 className={styles.portalTitle}>Este link de admissão não está disponível</h1><p className={styles.portalText}>{error}</p><p className={styles.itemMeta}>Fale com o RH para solicitar um novo link.</p></section></PortalFrame>
 return <PortalFrame progress={progress[current]} saved={saved}>{offline&&<div className={styles.docRow} style={{background:'#FFF9EE',color:'#8A5A06'}}><WifiOff size={15}/> Você está sem conexão. Seus dados serão preservados nesta tela.</div>}{error&&<div className={styles.docRow} style={{background:'#FBEAE7',color:'#A93226'}} role="alert">{error}<button style={{float:'right'}} onClick={()=>setError('')}>x</button></div>}
  <section className={styles.portalCard}>{current==='inicio'&&<Intro data={data!}/>} {current==='dados'&&<Personal form={form} set={set}/>} {current==='endereco'&&<Address token={token} form={form} set={set}/>} {current==='dados-bancarios'&&<Bank form={form} set={set}/>} {current==='dependentes'&&<Dependents value={dependents} set={setDependents}/>} {current==='vale-transporte'&&<Transport value={transport} set={setTransport}/>} {current==='documentos'&&<Documents data={data!} upload={uploadDoc}/>} {current==='foto'&&<Photo preview={photoPreview} choose={f=>{setPhoto(f);setPhotoPreview(URL.createObjectURL(f))}}/>} {current==='validacao-facial'&&<Face status={data?.faceVerification?.status}/>} {current==='revisao'&&<Review data={data!}/>} {current==='assinatura'&&<Signature token={token} data={data!} accepted={accepted} setAccepted={setAccepted}/>} {current==='conclusao'&&<Complete data={data!}/>}</section>
  {current!=='conclusao'&&<nav className={styles.portalNav}><button className={styles.button} onClick={back} disabled={index===0}><ChevronLeft size={15}/>Voltar</button><button className={styles.buttonPrimary} onClick={next[current]} disabled={offline||waitingFaceReview||current==='assinatura'&&!accepted}>{waitingFaceReview?'Aguardando análise':current==='inicio'?'Começar':current==='assinatura'?'Confirmar assinatura':'Continuar'}{!waitingFaceReview&&<ChevronRight size={15}/>}</button></nav>}
 </PortalFrame>
}
function PortalFrame({progress,saved,children}:{progress:number;saved:string;children:React.ReactNode}){return <div className={styles.portal}><header className={styles.portalHeader}><div className={styles.portalBrand}><img src="/bhcl-admissao-logo.png" alt="BHCL" style={{width:78,height:46,objectFit:'contain'}}/><span>Admissão Digital</span></div>{saved&&<span className={styles.saveState}><Check size={13}/>{saved}</span>}</header><main className={styles.portalMain}><div className={styles.portalProgress}><div className={styles.portalProgressMeta}><span>Seu progresso</span><strong>{progress}%</strong></div><div className={styles.progress}><span style={{width:`${progress}%`}}/></div></div>{children}</main></div>}
function Intro({data}:{data:PortalData}){return <><h1 className={styles.portalTitle}>Olá, {data.candidateName.split(' ')[0]}!</h1><p className={styles.portalText}>Vamos cuidar da sua admissão de forma simples e segura. Você pode parar e continuar depois pelo mesmo link.</p><div className={styles.docRow}><strong>Confira sua contratação</strong><div className={styles.summaryGrid} style={{marginTop:13}}><Summary l="Cargo" v={data.locked.jobTitle}/><Summary l="Unidade" v={data.locked.unit}/><Summary l="Data de admissão" v={new Date(data.locked.hireDate).toLocaleDateString('pt-BR')}/><Summary l="Contrato" v={data.locked.contractType}/></div></div><p className={styles.itemMeta}>Ao continuar, você confirma que este processo pertence a você. Seus dados internos de contratação não podem ser alterados neste portal.</p></>}
function Personal({form,set}:{form:any;set:(k:string,v:any)=>void}){
 const fields:PortalField[]=[
  {key:'name',label:'Nome completo'},
  {key:'birthDate',label:'Data de nascimento',type:'date'},
  {key:'phone',label:'Telefone',type:'tel',inputMode:'tel',format:formatPhone,maxLength:15},
  {key:'messagePhone',label:'Telefone de recado',type:'tel',inputMode:'tel',format:formatPhone,maxLength:15},
  {key:'email',label:'E-mail',type:'email',inputMode:'email'},
  {key:'cpf',label:'CPF',inputMode:'numeric',format:formatCpf,maxLength:14},
  {key:'rg',label:'RG',format:formatRg,maxLength:12},
  {key:'rgIssuedAt',label:'Data de expedição',type:'date'},
  {key:'rgIssuer',label:'Órgão emissor'},
  {key:'pis',label:'PIS',inputMode:'numeric',format:formatPis,maxLength:14},
  {key:'birthCity',label:'Cidade de nascimento'},
  {key:'ethnicity',label:'Etnia'},
  {key:'disability',label:'Pessoa com deficiência',options:['Não','Sim'],placeholder:'Selecione',onChange:value=>{set('disability',value);if(value!=='Sim')set('disabilityDetails','')}},
  ...(form.disability==='Sim'?[{key:'disabilityDetails',label:'Especifique a deficiência',required:true} satisfies PortalField]:[]),
  {key:'fatherName',label:'Nome do pai'},
  {key:'motherName',label:'Nome da mãe'},
  {key:'education',label:'Grau de instrução',options:EDUCATION_OPTIONS,placeholder:'Selecione'},
  {key:'maritalStatus',label:'Estado civil',options:MARITAL_STATUS_OPTIONS,placeholder:'Selecione'},
 ]
 return <><Title t="Identificação e contato" p="Preencha como aparece nos seus documentos."/><Fields items={fields} form={form} set={set}/></>
}
function Address({token,form,set}:{token:string;form:any;set:(k:string,v:any)=>void}){
 const [cepState,setCepState]=useState<'idle'|'loading'|'success'|'error'>('idle'),[cepMessage,setCepMessage]=useState('');const lastCep=useRef('')
 const cepDigits=onlyDigits(form.zipCode,8)
 useEffect(()=>{if(cepDigits.length!==8){lastCep.current='';setCepState('idle');setCepMessage('');return}if(lastCep.current===cepDigits)return;lastCep.current=cepDigits;const controller=new AbortController();const timer=setTimeout(async()=>{setCepState('loading');setCepMessage('Consultando CEP…');try{const response=await fetch(`/api/admissao/${token}/cep/${cepDigits}`,{signal:controller.signal}),result=await response.json();if(!response.ok)throw Error(result.error||'CEP não encontrado.');set('street',result.street||'');set('district',result.district||'');set('city',result.city||'');set('state',result.state||'');if(result.complement&&!form.complement)set('complement',result.complement);setCepState('success');setCepMessage('Endereço preenchido pelo CEP. Confira os dados.')}catch(error){if(error instanceof Error&&error.name==='AbortError')return;setCepState('error');setCepMessage(error instanceof Error?error.message:'Não foi possível consultar o CEP.')}} ,350);return()=>{clearTimeout(timer);controller.abort()}
 // A consulta só deve reiniciar quando o CEP completo mudar.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[cepDigits,token])
 return <><Title t="Onde você mora" p="Use o endereço que consta no comprovante de residência."/><Fields items={[{key:'zipCode',label:'CEP',inputMode:'numeric',format:formatCep,maxLength:9},{key:'street',label:'Endereço'},{key:'number',label:'Número'},{key:'complement',label:'Complemento'},{key:'district',label:'Bairro'},{key:'city',label:'Cidade'},{key:'state',label:'UF',maxLength:2}]} form={form} set={set}/>{cepMessage&&<p className={cepState==='error'?styles.error:styles.hint} role="status">{cepMessage}</p>}</>
}
function Bank({form,set}:{form:any;set:(k:string,v:any)=>void}){return <><Title t="Onde você receberá seu salário" p="A conta deve estar no seu nome."/><Fields items={[{key:'bank',label:'Banco'},{key:'agency',label:'Agência',inputMode:'numeric',format:formatAgency,maxLength:6},{key:'account',label:'Conta',inputMode:'numeric',format:formatAccount,maxLength:14},{key:'accountDigit',label:'Dígito',format:formatAccountDigit,maxLength:2},{key:'accountType',label:'Tipo de conta',options:ACCOUNT_TYPE_OPTIONS,placeholder:'Selecione'}]} form={form} set={set}/></>}
function Fields({items,form,set}:{items:PortalField[];form:any;set:(k:string,v:any)=>void}){return <div className={styles.formGrid}>{items.map(item=><label className={styles.field} key={item.key}><span className={styles.label}>{item.label}{item.required?' *':''}</span>{item.options?<select className={styles.select} name={item.key} required={item.required} value={form[item.key]??''} onChange={event=>(item.onChange||((value:string)=>set(item.key,value)))(event.target.value)}><option value="">{item.placeholder||'Selecione'}</option>{item.options.map(option=><option key={option} value={option}>{option}</option>)}</select>:<input className={styles.input} name={item.key} required={item.required} type={item.type||'text'} inputMode={item.inputMode} maxLength={item.maxLength} value={item.format?item.format(form[item.key]):form[item.key]??''} onChange={event=>{const value=item.format?item.format(event.target.value):event.target.value;(item.onChange||((next:string)=>set(item.key,next)))(value)}}/>}</label>)}</div>}
function Dependents({value,set}:{value:any[];set:(v:any[])=>void}){return <><Title t="Você tem dependentes?" p="Adicione quantos forem necessários. Você pode editar ou remover antes da assinatura."/>{value.map((d,i)=><div className={styles.docRow} key={i}><div className={styles.formGrid}><Input l="Nome" v={d.name} on={v=>set(value.map((x,j)=>j===i?{...x,name:v}:x))}/><Input l="CPF" v={d.cpf} inputMode="numeric" maxLength={14} format={formatCpf} on={v=>set(value.map((x,j)=>j===i?{...x,cpf:v}:x))}/><Input l="Data de nascimento" v={d.birthDate} type="date" on={v=>set(value.map((x,j)=>j===i?{...x,birthDate:v}:x))}/><Input l="Relação" v={d.relationship} on={v=>set(value.map((x,j)=>j===i?{...x,relationship:v}:x))}/></div><label className={styles.itemMeta}><input type="checkbox" checked={!!d.irrfDependent} onChange={e=>set(value.map((x,j)=>j===i?{...x,irrfDependent:e.target.checked}:x))}/> Dependente para IRRF</label>   <label className={styles.itemMeta}><input type="checkbox" checked={!!d.childUnder14} onChange={e=>set(value.map((x,j)=>j===i?{...x,childUnder14:e.target.checked}:x))}/> Filho menor de 14 anos</label><button className={styles.buttonDanger} style={{marginTop:10}} onClick={()=>set(value.filter((_,j)=>j!==i))}><Trash2 size={13}/>Remover</button></div>)}<button className={styles.button} onClick={()=>set([...value,{name:'',cpf:'',birthDate:'',relationship:'',irrfDependent:false,childUnder14:false}])}><Plus size={14}/>Adicionar dependente</button></>}
function Transport({value,set}:{value:any;set:(v:any)=>void}){return <><Title t="Você deseja receber Vale-Transporte?" p="Sua escolha e declaração ficam registradas no processo."/><div className={styles.choiceGrid}><button className={`${styles.choice} ${value.requested===true?styles.choiceActive:''}`} onClick={()=>set({...value,requested:true})}><strong>Sim, desejo receber</strong></button><button className={`${styles.choice} ${value.requested===false?styles.choiceActive:''}`} onClick={()=>set({...value,requested:false,routes:[]})}><strong>Não desejo receber</strong></button></div>{value.requested===false&&<div style={{marginTop:14}}><Input l="Motivo *" v={value.refusalReason} on={v=>set({...value,refusalReason:v})}/></div>}{value.requested===true&&<div style={{marginTop:14}}>{value.routes.map((r:any,i:number)=><div className={styles.docRow} key={i}><div className={styles.formGrid}><Input l="Tipo" v={r.type} on={v=>set({...value,routes:value.routes.map((x:any,j:number)=>j===i?{...x,type:v}:x)})}/><Input l="Linha" v={r.line} on={v=>set({...value,routes:value.routes.map((x:any,j:number)=>j===i?{...x,line:v}:x)})}/><Input l="Valor de ida" v={r.outbound} type="number" on={v=>set({...value,routes:value.routes.map((x:any,j:number)=>j===i?{...x,outbound:Number(v)}:x)})}/><Input l="Valor de volta" v={r.returnValue} type="number" on={v=>set({...value,routes:value.routes.map((x:any,j:number)=>j===i?{...x,returnValue:Number(v)}:x)})}/></div><div className={styles.itemMeta}>Total diário: {(Number(r.outbound||0)+Number(r.returnValue||0)).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</div></div>)}<button className={styles.button} onClick={()=>set({...value,routes:[...value.routes,{type:'Ônibus',line:'',outbound:0,returnValue:0}]})}><Plus size={14}/>Adicionar linha ou trecho</button></div>}<label className={styles.docRow} style={{display:'block',marginTop:16}}><input type="checkbox" checked={!!value.declarationAccepted} onChange={e=>set({...value,declarationAccepted:e.target.checked})}/> <span className={styles.itemMeta}>Declaro que as informações prestadas são verdadeiras e autorizo o tratamento para fins de concessão do benefício, conforme texto vigente validado pela BHCL.</span></label></>}
function Documents({data,upload}:{data:PortalData;upload:(id:string,file?:File)=>void}){return <><Title t="Seus documentos" p="Fotografe com boa luz ou selecione PDF, JPG ou PNG. As quatro bordas devem aparecer."/>{data.documents.map(d=><div className={styles.docRow} key={d.id}><div style={{display:'flex',gap:10,alignItems:'center'}}><div style={{flex:1}}><strong>{d.type.name}</strong><div className={styles.itemMeta}>{d.type.required?'Obrigatório':'Opcional'} · até {Math.round(d.type.maxSizeBytes/1048576)} MB</div></div><StatusBadge status={d.status}/></div>{d.rejectionReason&&<p className={styles.error}>{d.rejectionReason}</p>}<label className={styles.button} style={{marginTop:10}}><FileUp size={14}/>{d.status==='PENDING'?'Enviar arquivo':'Reenviar'}<input hidden type="file" accept="application/pdf,image/jpeg,image/png" capture="environment" onChange={e=>upload(d.id,e.target.files?.[0])}/></label></div>)}</>}
function Photo({preview,choose}:{preview:string;choose:(f:File)=>void}){return <><Title t="Vamos tirar sua foto do crachá" p="Fique de frente, use fundo claro, retire acessórios que cubram o rosto e não aplique filtros."/><div className={styles.cameraFrame}>{preview?<img src={preview} alt="Prévia da foto"/>:<Camera size={46}/>}</div><label className={styles.buttonPrimary} style={{width:'100%'}}><Camera size={15}/>{preview?'Refazer foto':'Abrir câmera'}<input hidden type="file" accept="image/jpeg,image/png" capture="user" onChange={e=>e.target.files?.[0]&&choose(e.target.files[0])}/></label></>}
function Face({status}:{status?:string}){return <><Title t="Confirme que é você" p="Vamos comparar sua foto com o documento de identidade aprovado. O RH revisará resultados inconclusivos."/><div className={styles.cameraFrame}><div style={{textAlign:'center'}}><Camera size={44}/><p>Sua foto será processada com acesso restrito</p></div></div>{status&&<StatusBadge status={status}/>}<p className={styles.itemMeta}>{status==='MANUAL_REVIEW'?'A comparação foi encaminhada para análise humana. Nenhuma ação é necessária agora.':'A validação é processada no servidor. Credenciais e resultados técnicos não são enviados ao navegador.'}</p></>}
function Review({data}:{data:PortalData}){const approved=data.documents.filter(d=>d.status==='APPROVED').length,pending=data.documents.filter(d=>d.type.required&&d.status!=='APPROVED').length;return <><Title t="Revise seus documentos" p="Confirme se todas as etapas foram concluídas antes de gerar os documentos admissionais."/><div className={styles.metricList}><div className={styles.docRow}><strong>Dados pessoais</strong><div className={styles.itemMeta}>Preenchidos e salvos</div></div><div className={styles.docRow}><strong>Documentos enviados</strong><div className={styles.itemMeta}>{approved} aprovados · {pending} pendentes</div></div><div className={styles.docRow}><strong>Validação facial</strong><div className={styles.itemMeta}>{data.faceVerification?.status||'Não iniciada'}</div></div></div>{pending>0&&<p className={styles.error}>O RH ainda precisa aprovar {pending} documento(s). Você poderá continuar depois pelo mesmo link.</p>}</>}
function Signature({token,data,accepted,setAccepted}:{token:string;data:PortalData;accepted:boolean;setAccepted:(v:boolean)=>void}){return <><Title t="Assinatura eletrônica" p="Leia cada documento antes de assinar. Você poderá baixar todos depois."/>{data.generatedDocuments.map(d=><a className={styles.docRow} style={{display:'block'}} key={d.id} href={`/api/admissao/${token}/documentos-gerados/${d.id}/arquivo`} target="_blank"><strong>{d.name||'Documento admissional'}</strong><div className={styles.itemMeta}>Versão {d.version} · visualizar PDF</div></a>)}<label className={styles.docRow} style={{display:'block'}}><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/> Li e estou de acordo com os documentos acima.</label><div className={styles.itemMeta}>Ao confirmar, sua assinatura fica vinculada à versão, hash, data, IP e transação registrados.</div></>}
function Complete({data}:{data:PortalData}){return <div style={{textAlign:'center'}}><div style={{width:58,height:58,borderRadius:'50%',background:'#E6F4EC',color:'#1E8E5A',display:'grid',placeItems:'center',margin:'0 auto 16px'}}><Check size={28}/></div><h1 className={styles.portalTitle}>Tudo certo, {data.candidateName.split(' ')[0]}!</h1><p className={styles.portalText}>Seu processo de admissão foi concluído e será integrado aos sistemas da BHCL.</p><div className={styles.docRow}><Summary l="Protocolo" v={data.protocol}/><Summary l="Situação" v="Assinatura concluída"/></div></div>}
function Title({t,p}:{t:string;p:string}){return <><h1 className={styles.portalTitle}>{t}</h1><p className={styles.portalText}>{p}</p></>}
function Input({l,v,on,type='text',inputMode,format,maxLength}:{l:string;v:any;on:(v:string)=>void;type?:string;inputMode?:'text'|'numeric'|'tel'|'email';format?:(value:unknown)=>string;maxLength?:number}){return <label className={styles.field}><span className={styles.label}>{l}</span><input className={styles.input} type={type} inputMode={inputMode} maxLength={maxLength} value={format?format(v):v??''} onChange={e=>on(format?format(e.target.value):e.target.value)}/></label>}
function Summary({l,v}:{l:string;v:string}){return <div><div className={styles.summaryLabel}>{l}</div><div className={styles.summaryValue}>{v||'—'}</div></div>}
