import { NextRequest,NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getAdmissionByPublicToken } from '@/lib/admission/service'
import { mockSignatureProvider } from '@/lib/admission/providers'
import { generateAdmissionDocuments } from '@/lib/admission/documentGenerator'
import { logAdmissionEvent } from '@/lib/admission/audit'
import { extractIp } from '@/lib/audit'

export async function POST(req:NextRequest,{params}:{params:{token:string}}){const token=await getAdmissionByPublicToken(params.token);if(!token)return NextResponse.json({error:'Link inválido ou expirado.'},{status:404});const body=await req.json().catch(()=>({}));if(!body.accepted)return NextResponse.json({error:'Confirme a leitura e concordância.'},{status:400});const pending=token.admission.documents.some(d=>d.type.required&&d.status!=='APPROVED');if(pending)return NextResponse.json({error:'Ainda existem documentos obrigatórios pendentes.'},{status:409});const docs=token.admission.generatedDocuments.length?token.admission.generatedDocuments:await generateAdmissionDocuments(token.admissionId,req.nextUrl.origin);for(const doc of docs){let envelope=await prisma.signatureEnvelope.findFirst({where:{documentId:doc.id}});if(!envelope)envelope=await prisma.signatureEnvelope.create({data:{admissionId:token.admissionId,documentId:doc.id,provider:process.env.SIGNATURE_PROVIDER||'mock',signerName:token.admission.candidateName,signerEmail:token.admission.candidateEmail,status:'AUTHENTICATED'}});if(envelope.status!=='SIGNED'){const signed=await mockSignatureProvider.sign(envelope.id);await prisma.$transaction([prisma.signatureEnvelope.update({where:{id:envelope.id},data:{status:'SIGNED',transactionId:signed.transactionId,signedAt:signed.signedAt}}),prisma.signatureEvent.create({data:{envelopeId:envelope.id,type:'SIGNED',ip:extractIp(req.headers),userAgent:req.headers.get('user-agent'),metadata:{provider:'mock'}}}),prisma.generatedDocument.update({where:{id:doc.id},data:{status:'SIGNED',signedAt:signed.signedAt,finalHash:doc.originalHash}})])}}
 await prisma.$transaction([prisma.admission.update({where:{id:token.admissionId},data:{status:'READY_FOR_ERPNEXT',currentStep:'conclusao',progress:100,lastActivityAt:new Date()}}),prisma.eRPNextSync.upsert({where:{idempotencyKey:`admission:${token.admissionId}`},create:{admissionId:token.admissionId,idempotencyKey:`admission:${token.admissionId}`,status:'WAITING',nextAttemptAt:new Date()},update:{status:'WAITING',nextAttemptAt:new Date(),lastError:null}}),prisma.consentRecord.create({data:{admissionId:token.admissionId,type:'ELECTRONIC_SIGNATURE',version:'v1',accepted:true,ip:extractIp(req.headers),userAgent:req.headers.get('user-agent')}})]);await logAdmissionEvent({admissionId:token.admissionId,actorName:token.admission.candidateName,actorType:'CANDIDATE',action:'DOCUMENTS_SIGNED',ip:extractIp(req.headers),userAgent:req.headers.get('user-agent'),metadata:{documentCount:docs.length,provider:'mock'}});return NextResponse.json({success:true,protocol:token.admission.protocol})}
