// GERADO a partir dos textos aprovados (contrato v2 + carga mensal, vale-transporte v2) e do formulário admissional.
// São gravados em `DocumentTemplate` na primeira geração de documentos (ver ensureAdmissionTemplates);
// depois disso o banco é a fonte da verdade e novas versões podem ser criadas sem alterar código.

export type AdmissionTemplateDefault = { key: string; name: string; version: number; content: string }

export const ADMISSION_TEMPLATE_DEFAULTS: AdmissionTemplateDefault[] = [
  {
    "key": "contrato_trabalho",
    "name": "Contrato de Experiência",
    "version": 3,
    "content": "CONTRATO INDIVIDUAL DE TRABALHO — CONTRATO DE EXPERIÊNCIA\n\nPelo presente instrumento particular de Contrato de Experiência, {{employerName}}, com sede em {{employerAddress}}, inscrita no CNPJ sob nº {{employerCnpj}}, doravante denominada EMPREGADORA, e {{candidateName}}, CPF nº {{cpf}}, RG nº {{rg}}, domiciliado(a) em {{addressFull}}, doravante denominado(a) EMPREGADO(A), firmam o presente contrato individual de trabalho, regido pelas cláusulas seguintes:\n\n1 — FUNÇÃO\nO(A) EMPREGADO(A) trabalhará para a EMPREGADORA na função de {{jobTitle}}, no departamento {{department}}, executando também atividades compatíveis com suas atribuições e determinadas pela EMPREGADORA.\n\n2 — LOCAL DE TRABALHO\nO local principal de trabalho será a unidade {{unit}}. A transferência temporária ou definitiva observará as hipóteses e condições previstas na legislação trabalhista vigente.\n\n3 — JORNADA\nHorário de trabalho: {{workSchedule}}.\nIntervalo: {{breakSchedule}}.\nCarga horária mensal: {{monthlyHours}}.\n\n4 — REMUNERAÇÃO\nO(A) EMPREGADO(A) receberá salário mensal de {{salary}}. Adicional de insalubridade informado para a contratação: {{hazardPayPercentage}}.\n\n5 — PRAZO\nEste contrato inicia-se em {{hireDate}}, pelo prazo de {{experienceDays}}, com término previsto em {{contractEndDate}}. Eventual prorrogação deverá ser formalizada e respeitar os limites legais.\n\n6 — DESCONTOS E RESPONSABILIDADES\nAlém dos descontos previstos em lei, poderão ser descontadas as importâncias correspondentes a danos causados pelo(a) EMPREGADO(A), quando presentes os requisitos legais aplicáveis.\n\n7 — NORMAS INTERNAS E SEGURANÇA\nO(A) EMPREGADO(A) declara ciência do regulamento interno, das normas de segurança e da obrigação de utilizar os equipamentos de proteção fornecidos para o exercício de suas atividades.\n\n8 — CONTINUIDADE\nPermanecendo o(a) EMPREGADO(A) a serviço da EMPREGADORA após o término da experiência, continuarão em vigor as cláusulas compatíveis deste contrato, observada a legislação aplicável.\n\n9 — RESCISÃO ANTECIPADA\nA rescisão antecipada observará as disposições legais aplicáveis aos contratos por prazo determinado, inclusive os artigos 479 e 480 da Consolidação das Leis do Trabalho, quando cabíveis.\n\nDADOS DA ADMISSÃO\nProtocolo: {{protocol}}\nTipo de contratação: {{contractType}}\nVaga: {{vacancyTitle}}\nData de admissão: {{hireDate}}\nUnidade: {{unit}}\n\nDADOS DO(A) EMPREGADO(A)\nNome: {{candidateName}}\nData de nascimento: {{birthDate}}\nCPF: {{cpf}}\nRG: {{rg}} — órgão emissor {{rgIssuer}} — expedição {{rgIssuedAt}}\nPIS: {{pis}}\nEstado civil: {{maritalStatus}}\nGrau de instrução: {{education}}\nFiliação: {{fatherName}} / {{motherName}}\nEndereço: {{addressFull}}\nTelefone: {{phone}}\nE-mail: {{email}}\n\nAs partes declaram que leram e compreenderam este instrumento. A assinatura eletrônica e suas evidências técnicas serão anexadas ao PDF final.\n\n{{city}}, {{signatureDateLong}}.\n"
  },
  {
    "key": "termo_vale_transporte",
    "name": "Vale-Transporte — Declaração e Termo de Compromisso",
    "version": 2,
    "content": "VALE-TRANSPORTE — DECLARAÇÃO E TERMO DE COMPROMISSO\n\nNome: {{candidateName}}\nCPF: {{cpf}}\nCargo: {{jobTitle}}\nData de admissão: {{hireDate}}\nEndereço: {{street}}, nº {{number}}\nBairro: {{district}}    UF: {{state}}    CEP: {{zipCode}}\n\nESCLARECIMENTOS LEGAIS\nO Vale-Transporte será pago pelo Beneficiário até 6% (seis por cento) de seu salário (excluídos quaisquer adicionais e vantagens) e pelo empregador, no que exceder a esse limite.\nNo caso em que o valor total dos vales-transporte recebidos for inferior a 6% (seis por cento) do salário, o empregador poderá optar pelo recebimento antecipado de vales-transporte, cujo valor será integralmente descontado por ocasião do pagamento do respectivo salário.\n\nOPÇÃO PELO VALE-TRANSPORTE\nNão é permitido substituir o fornecimento do vale-transporte por antecipação em dinheiro ou qualquer outra forma de pagamento, salvo no caso de falta ou insuficiência de estoque de vale-transporte.\n{{transportYes}} SIM, necessito do benefício do Vale-Transporte (trajetos informados abaixo).\n{{transportNo}} NÃO necessito do benefício do Vale-Transporte. Motivo: {{transportRefusalReason}}\n\nTRAJETOS INFORMADOS\n{{transportRoutesTable}}\nValor total por dia (ida + volta): {{transportDailyTotal}}\n\nTERMO DE COMPROMISSO\nComprometo-me a atualizar as informações deste documento sempre que ocorrerem alterações, e a utilizar os Vales-Transporte que me forem concedidos exclusivamente no percurso residência-trabalho e vice-versa.\nEstou ciente de que, na hipótese de infringir tal compromisso, a Empresa poderá dispensar-me por justa causa, nos termos do Art. 7º, parágrafo 3º, do Decreto nº 95.247/1987.\nAutorizo a Empresa a descontar mensalmente de meus vencimentos, até o limite de 6% (seis por cento) do meu salário, o valor destinado a cobrir o fornecimento de Vales-Transporte por mim utilizados.\n\n{{city}}, {{signatureDateLong}}.\n"
  },
  {
    "key": "ficha_registro",
    "name": "Formulário Admissional",
    "version": 2,
    "content": "FORMULÁRIO ADMISSIONAL — FICHA DE REGISTRO DO EMPREGADO\n\nEmpresa: {{employerName}} — CNPJ {{employerCnpj}}\nProtocolo: {{protocol}}\n\nDADOS PESSOAIS\nNome: {{candidateName}}\nCPF: {{cpf}}\nRG: {{rg}} — órgão emissor {{rgIssuer}} — expedição {{rgIssuedAt}}\nPIS/PASEP: {{pis}}\nData de nascimento: {{birthDate}}\nEstado civil: {{maritalStatus}}\nGrau de instrução: {{education}}\nNome da mãe: {{motherName}}\nNome do pai: {{fatherName}}\nTelefone: {{phone}}\nE-mail: {{email}}\n\nENDEREÇO\n{{addressFull}}\n\nDADOS DA CONTRATAÇÃO\nCargo: {{jobTitle}}\nDepartamento: {{department}}\nUnidade: {{unit}}\nData de admissão: {{hireDate}}\nTipo de contrato: {{contractType}}\nSalário: {{salary}}\nAdicional de insalubridade: {{hazardPayPercentage}}\nHorário de trabalho: {{workSchedule}}\nCarga horária mensal: {{monthlyHours}}\n\nDADOS BANCÁRIOS\nBanco: {{bankName}}\nAgência: {{bankAgency}}\nConta: {{bankAccount}} ({{bankAccountType}})\n\nDEPENDENTES\n{{dependents}}\n\nVALE-TRANSPORTE\nOpção: {{transportChoice}}\n\nDeclaro que as informações acima são verdadeiras e me comprometo a comunicar ao empregador qualquer alteração.\n\n{{signatureDateLong}}.\n"
  }
]
